### ISSUE TITLE
Improve storage errors

### ISSUE THREAD

**Issue by 2opremio** [stellar/rs-soroban-env#1008]
When calling `host.invoke_function()`, if a ledger entry is missing (e.g. due to a badly constructed contract invocation), the following error message is returned:

```
HostError: Error(Storage, MissingValue)
DebugInfo not available
```

(note that this is before invoking `host.try_finish()` and thus there are no diagnostic events).

I would expect the error to tell me the key  of the missing ledger entry. Also, `(Storage, MissingValue)` isn't helpful since it doesn't tell the user it's a LedgerEntry which is missing.

In general, I think any errors returned by `host.invoke_function()`  before `try_finish()` should be descriptive and add context, since there are no diagnostic events.

**Comment by 2opremio** [comment]
CC @dmkozh

**Comment by 2opremio** [comment]
I have seen that I can recover diagnostic events in `try_finish()` even if `invoke_function()` fails (which is awkward).

But even them the diagnostic events are not useful.

Here's the XDR of the only event returned:

`AAAAAAAAAAAAAAAAAAAAAgAAAAAAAAADAAAADwAAAAdmbl9jYWxsAAAAAA0AAAAgAQIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAE=`

**Comment by 2opremio** [comment]
Here's the unmarshalled event:

<img width="689" alt="Screenshot 2023-08-21 at 03 07 04" src="https://github.com/stellar/rs-soroban-env/assets/2362916/62dd9056-5d5d-4b7e-b87c-5e51fd43cd4f">

**Comment by anupsdf** [comment]
Hi @2opremio, Can you re-evaluate this with latest preview 11 build, please.

**Comment by anupsdf** [comment]
This can be closed since we are have lot of improved error handling. Please open a new issue if there are any other areas we can improve.
