### ISSUE TITLE
Improve host errors in general

### ISSUE THREAD

**Issue by 2opremio** [stellar/rs-soroban-env#1021]
Here's another Host error which isn't very helpful:

```
    HostError: Error(Auth, InvalidInput)
    DebugInfo not available
```

It doesn't tell you why the input is invalid.

But please please review and improve host errors in general, not just the examples we report in tickets.

More context at https://github.com/stellar/soroban-tools/pull/855#issuecomment-1692182998

Related #1008

**Comment by 2opremio** [comment]
CC @anupsdf

**Comment by graydon** [comment]
Why are you getting no debuginfo? Are you running with diagnostic level not set to debug?

**Comment by 2opremio** [comment]
In this case it seems we were not collecting diagnostic events properly (see https://github.com/stellar/soroban-tools/pull/855 ). Let's keep the ticket open until we confirm there were diagnostic events and that they were useful.

@sreuland can you please check?

**Comment by sreuland** [comment]
running system-test off latest on soroban-tools/main, seeing the same simulation response from a cli attempt on `contract deploy` :

```
running command soroban [contract deploy --wasm-hash 9e91a6c6234cf7a43fde49739fec8f2c2f40b9fdb068650e7a590e3791731bc7 --rpc-url http://localhost:8000/soroban/rpc --source SC5O7VZUXDJ6JBDSZ74DSERXL7W3Y5LTOAMRF7RQRL3TAGAPS7LUVG3L --network-passphrase Standalone Network ; February 2017] 

error: transaction simulation failed: cannot set authorization entries

Caused by:
    HostError: Error(Auth, InternalError)
    DebugInfo not available

```


https://github.com/stellar/soroban-tools/actions/runs/6052719647/job/16426740644?pr=855#step:8:1329

**Comment by anupsdf** [comment]
@2opremio , Can you re-evaluate this with the latest preview 11 build and let us know if you still don't see helpful error message? We have done lot of improvements in plumbing the error messages out of env.

**Comment by dmkozh** [comment]
We've made a lot of improvements to diagnostic events since this issue has been created. There could be gaps, but I think they deserve separate issues, so I'll close this one.
