### ISSUE TITLE
Host::check_val_integrity could/should error on bad tags

### ISSUE THREAD

**Issue by brson** [stellar/rs-soroban-env#1029]
`Host::check_val_integrity` is called on all Vals passing through the Host. This avoids contracts receiving adversarial "weird" Vals from other contracts.

At the moment it appears to only reject Vals that are objects that have invalid references.

Another type of unexpected Val is one with an invalid tag (Tag::Bad). The host could also reject these.

cc "adversarial" vals for fuzzing https://github.com/stellar/rs-soroban-sdk/issues/1052

**Comment by graydon** [comment]
Agreed, good idea.

**Comment by graydon** [comment]
Fixed in #1033
