### ISSUE TITLE
Null characters rendered in assets codes of built-in Stellar Asset Contract

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#1032]
### What version are you using?

- stellar/soroban-tools@b1519a4d90502ce3155960541b2a98c88f3dd043 (rpc and cli)
- stellar/stellar-core@22b9bb38416e5ce058eb9c1fadfdd414a4661833
- stellar/rs-soroban-env@eb5a9ba053a7b64a8eff605db625525378f7bea0

### What did you do?

```console
❯ soroban lab token wrap --network local --source me --asset USD:GDP7GGFMNMWABGWTF6BUB45MN6TPOCFY43KJVK5LDBCSJ2QTMQYYU3DA
CAW7SH5JG45U6YLCFB6YD2KVSOZQHMNEJQPN6KDZOCGSXWR72ZIFBBMP

❯ soroban contract invoke --network local --source me --id CAW7SH5JG45U6YLCFB6YD2KVSOZQHMNEJQPN6KDZOCGSXWR72ZIFBBMP -- name
```

The `local` network is a local quickstart running the commits above.

The `me` source is the networks root account.

### What did you expect to see?

```console
❯ soroban contract invoke --network local --source me --id CAW7SH5JG45U6YLCFB6YD2KVSOZQHMNEJQPN6KDZOCGSXWR72ZIFBBMP -- name
"USD:GDP7GGFMNMWABGWTF6BUB45MN6TPOCFY43KJVK5LDBCSJ2QTMQYYU3DA"
```

### What did you see instead?

```console
❯ soroban contract invoke --network local --source me --id CAW7SH5JG45U6YLCFB6YD2KVSOZQHMNEJQPN6KDZOCGSXWR72ZIFBBMP -- name
"USD\u0000:GDP7GGFMNMWABGWTF6BUB45MN6TPOCFY43KJVK5LDBCSJ2QTMQYYU3DA"
```

### Discussion

Stellar assets have two types of asset codes, a 4 byte and 12 byte code. The specification of less than a 4 byte asset code when wrapping is selecting the 4 byte asset type, and the remaining characters are null (`\u0000`).

When rendering the asset to a string, it should be rendered without the null bytes. The null bytes are indicative of the string ending early, and not of characters that are meaningfully part of the code itself.

See [SEP-11](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0011.md#alphanum4-alphanum12) for the correct rendering of the asset code.

**Comment by graydon** [comment]
Ok I _think_ this is basically originating [here](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/metadata.rs#L23-L51) which is delegating to the native-contract wrapper type String that wraps the host type String, and asking it to render itself as a Rust String. The whole codepath there is actually fairly weak and wrong (doesn't do metering, doesn't do any of the suggested SEP-11 stuff) and arguably Rust Strings shouldn't be involved at all.
