### ISSUE TITLE
Double counting readWrite.size when computing Soroban resource fees

### ISSUE THREAD

**Issue by anupsdf** [stellar/rs-soroban-env#1036]
### We are double counting readWrite.size when computing Soroban resource fees
When computing fees, the write_entries are being double counted.

In core, [TransactionFrame::computeSorobanResourceFee](https://github.com/stellar/stellar-core/blob/master/src/transactions/TransactionFrame.cpp#L791-L795) we compute the read/write entries as below,
```
cxxResources.read_entries = readOnly.size() + readWrite.size()
cxxResources.write_entries = readWrite.size()
```

Then it calls rust_bridge::compute_transaction_resource_fee. In env, we double count the readWrite.size() in [fees::compute_transaction_resource_fee](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/fees.rs#L142-L147)
`ledger_read_entry_fee = (read_entries + write_entries ) * fee_per_read_entry`

**Comment by dmkozh** [comment]
Seems like this is fixed now - thanks @SirTyson
