### ISSUE TITLE
Need to charge rent when contract data entry is updated to take extra storage space

### ISSUE THREAD

**Issue by anupsdf** [stellar/rs-soroban-env#1037]
### Not charging rent when contract data entry is updated to take extra storage space
`Context:` In Core, the result from calling e2e_invoke::invoke_host_function is used to call e2e_invoke::extract_rent_changes, [here](https://github.com/stellar/stellar-core/blob/master/src/rust/src/contract.rs#L364).

`Bug:` For a contract data key, if the contract data value is changed to take more space, then we are not charging rent for the increase in extra storage space. In [get_ledger_changes](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/e2e_invoke.rs#L138-L142), we set expiration to max of old and new ledger entry. Later in extract_rent_changes, we skip rent calculation when old_expiration >= new expiration since we return None.

fn get_ledger_changes
```
// Never reduce the final expiration ledger.
expiration_change.new_expiration_ledger = max(
    new_expiration_ledger.ok_or_else(|| internal_error.clone())?,
    expiration_change.old_expiration_ledger,
);
```

fn [extract_rent_changes](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/e2e_invoke.rs#L182-L187)
```
// Skip non-bumped entries as well.
if expiration_change.old_expiration_ledger >= expiration_change.new_expiration_ledger
{
    return None;
}

```
fees::[compute_rent_fee](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/fees.rs#L251C1-L251C31) only loops over the changed entries returned from extract_rent_changes in core [here](https://github.com/stellar/stellar-core/blob/master/src/rust/src/contract.rs#L364-L365).

**Comment by dmkozh** [comment]
Nice catch, thanks for fixing this!
