### ISSUE TITLE
`VecEntry` contract cost parameters are zero

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#1051]
The `VecEntry` is a cheap operation which just indexes into a fixed sized vector. The calibration code did not pick up the cost signal and produced zeros. While it's not vulnerable (one cannot index into a vector without creating it or doing something else that does cost non-trivial cpu), we need to fix it and add some cost. Probably just need to tweak the calibration setup a bit or increase the run iterations.

**Comment by anupsdf** [comment]
Putting prior information from Jay here,
`With this issue the indexing into the MeteredVector is free, but the usage of MeteredVector is not free. Usage is dominated by memcpy and memalloc. Indexing into host object from the user also requires the user calling a host function which has non-trivial cost.`

**Comment by jayz22** [comment]
Resolved by https://github.com/stellar/rs-soroban-env/pull/1105. Both `VecEntry` and `MapEntry` has been consolidated into `MemCpy`.
