### ISSUE TITLE
Inconsistent metering of `metered_vm_scan_slices_in_linear_memory`

### ISSUE THREAD

**Issue by dmkozh** [stellar/rs-soroban-env#1057]
`metered_vm_scan_slices_in_linear_memory` doesn't charge budget for reading the slices from the VM (it only charges for reading the slice pointers). One of the callbacks correctly charges for the slice read, but not the other two. We probably should be just charging for mem read inside `metered_vm_scan_slices_in_linear_memory` function itself and remove charging from the callbacks (these probably shouldn't worry about budget accounting for low-level ops).

**Comment by jayz22** [comment]
Those `metered_vm_.. ` functions are correctly charging for the exact amount of `MemCpy` (which are the pointers) inside itself. The callback functions need to charge for what's being done in it, which the `metered_vm..` don't know about and can't charge on their behalf. Most gaps are in those callbacks. 
I've addressed them in https://github.com/stellar/rs-soroban-env/pull/1115 and added some comments in the code.
