### ISSUE TITLE
Drawing PRNG bytes is unmetered

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#1059]
https://github.com/stellar/rs-soroban-env/blob/f19ef13363a1e0cbff7b100c0599a1d63dea88a6/soroban-env-host/src/host/prng.rs#L88

**Comment by jayz22** [comment]
This will require adding a new variant `ContractCostType::PrngDrawBytes` in the [xdr](https://github.com/stellar/stellar-xdr/blob/curr/Stellar-contract-config-setting.x#L92C14-L92C14), and doing calibration add a new cost model for it in the `Budget`.

**Comment by anupsdf** [comment]
The XDR change will go to both curr and next branches I think.
