### ISSUE TITLE
Change how 'free' budget works

### ISSUE THREAD

**Issue by dmkozh** [stellar/rs-soroban-env#1061]
Currently `with_free_budget` just disables the budget metering completely. While this is conceptually correct (as the respective calls shouldn't be included into the final metering result), it makes the live of the users of the debug mode harder due to full lack of metering harness.

A simple fix would be as follows:

- Add a second budget object ('free budget'), with limits set to some customizable ratio from the 'main' budget (e.g. 1 or 1/2.)
- Switch to the second budget when calling `with_free_budget`. Thus the debug calls will remain unobservable for the 'real' metering, while still bounding the contract execution time.
- 
- (Probably the most annoying part) Make sure the callbacks used with `with_free_budget` are metered using more or less the same metering standards we use for all the host codebase (basically we need to stay within O(1) of the actual work performed).

The side effect of this is that functions might fail due to exceeding the 'free' budget while logging. This is an edge case, though, so it shouldn't matter much.

Additionally, we might want to make `with_free_budget` infallible and simply be a no-op when the 'free' budget is exceeded. This doesn't significantly improve the preflight experience for the edge case above, but would ensure that core nodes with debug enabled won't have divergent contract execution results (they might have divergent results currently due to errors during the 'debug-only' operations).

**Comment by graydon** [comment]
(A small suggestion: if we're going to do this, which is fine by me, we should probably call the "free" budget the "debug" budget, for simplicity sake. It'll just confuse people otherwise)

**Comment by graydon** [comment]
Another possible thing to backstop DoS scenarios that either slip through review or happen in diagnostic mode: we could wrap the whole thing in https://docs.rs/context-allocator/latest/context_allocator/allocators/struct.BumpAllocator.html or some similar fixed-size global allocator so panic out on too-much-memory rather than actually using too much malloc memory.

**Comment by graydon** [comment]
Bumping this to a P0 and blocking final on it -- too risky a DoS vector on RPC servers to ship without this fixed.
