### ISSUE TITLE
ComputeEcdsaSecp256k1Key is never used

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#1087]
The interface we settled on for Secp256k1 is the "key recovery" interface which doesn't involve a user ever converting a bytes object directly to a public key. This cost is therefore never used (and the codepaths that do it are only used to calibrate the cost, never actually do it).

It should probably be removed from the XDR cost types.

**Comment by jayz22** [comment]
Xdr change has been merged. Env change will be made with https://github.com/stellar/rs-soroban-env/pull/1105.
