### ISSUE TITLE
Log {} substitution isn't working

### ISSUE THREAD

**Issue by tyvdh** [stellar/rs-soroban-env#1093]
Context on Discord
https://discord.com/channels/897514728459468821/1159181238398099474

In https://soroban.stellar.org/docs/basic-tutorials/logging#using-the-log-macro it's stated that
> Arguments are substituted wherever the {} value appears in the format string.

However when running this example I'm getting this error which 
A) makes it seem like logs are formatted differently and
B) makes it seem we are no longer doing substitutions for `{}`.

```bash
running 1 test
thread 'test::test' panicked at src/test.rs:16:5:
assertion `left == right` failed
  left: ["[Diagnostic Event] contract:d5897165b726ee309158a9e05ef0e3329f16eacf10e419d54121bd2059422278, topics:[log], data:[\"Hello {}\", Dev]"]
 right: ["Hello Symbol(Dev)"]
```

**Comment by graydon** [comment]
Yeah, this was a feature removed from logging, which there are no plans to re-add. log messages that want to include multiple data values should include them as multiple data values trailing a fixed string message, the host isn't going to format/interpolate values into the string. (b) is the correct interpretation. the docs are old.

**Comment by leighmcculloch** [comment]
Also, the reason the logs are formatted differently is to include additional information about contract IDs. In the past it was difficult to see which contract was logging data when multiple contracts were in play.
