### ISSUE TITLE
Host::call_account_contract_check_auth requires Contract ID as a BytesN<32> instead of as an Address

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#1099]
### What version are you using?

`20.0.0-rc2`

### What did you do?

Call `Host::call_account_contract_check_auth` with a contract `Address`.

### What did you expect to see?

🥳 

### What did you see instead?

Compile error because the function requires the contract to be given as a `BytesObject`.

### Discussion

This issue is blocking:
- https://github.com/stellar/rs-soroban-sdk/issues/1109

**Comment by sisuresh** [comment]
This has been resolved - https://github.com/stellar/rs-soroban-env/blob/74c3c045b7e607cfda9155c1bc00e897b5e5a19f/soroban-env-host/src/auth.rs#L2255
