### ISSUE TITLE
Investigate non-linearity of mem cost types on x86

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#1108]
Follow up on: https://github.com/stellar/rs-soroban-env/issues/1020#issuecomment-1755949046

**Comment by jayz22** [comment]
The cost types need to look into (after the latest round of consolidation):
- MemAlloc
- MemCpy
- MemCmp
- ValSer
- ValDeser

**Comment by graydon** [comment]
Adopted an analytic model for these rather than empirical
