### ISSUE TITLE
Bump wasmi before finalize

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#1137]
Recent changes i.e. https://github.com/paritytech/wasmi/pull/773 looks like a relevant and important fix. We should update Wasmi to the upstream before finalizing protocol 20. Thanks @anupsdf for pointing it out.

**Comment by graydon** [comment]
this is related to wasmi's new register machine backend, which is not enabled yet. we're still using its earlier / default (stack machine) backend.

**Comment by graydon** [comment]
(that said I agree it wouldn't hurt to take a wasmi update before we freeze, maybe to the last actual release though)

**Comment by jayz22** [comment]
Closing as completed.
