### ISSUE TITLE
[test] some invalid data-conversion cases

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#1147]
A grab bag of invalid conversions we aren't currently testing the conversion of:

- Outgoing conversion (Val -> ScVal):
  - [x] Amplified (bushy, not deep, eg. 10 layers each branching 10 ways) map and vec data structures
  - [ ] Invalid object handles
  - [ ] Invalid Val payloads (bad bit patterns)
- Incoming conversion (ScVal -> Val):
  - [x] Invalid XDR tag cases
  - [x] Oversized XDR input
- Both directions:
  - [ ] Invalid symbols
  - [ ] mis-ordered maps (half-done: `scmap_out_of_order` tests the input direction)
  - [ ] maps with duplicates
  - [ ] maps and vecs with invalid elements

**Comment by dmkozh** [comment]
> Amplified (bushy, not deep, eg. 10 layers each branching 10 ways) map and vec data structures

Covered by https://github.com/stellar/stellar-core/pull/4041

> Incoming conversion (ScVal -> Val):
>  Invalid XDR tag cases
>  Oversized XDR input

Will be covered by https://github.com/stellar/rs-soroban-env/issues/1162 (and is partially covered already). Note, that we can't really have invalid `ScVal` structure itself, because that should fail during de-serialization.
