### ISSUE TITLE
[test] failing variant of update-wasm test

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#1149]
Add a variant of `test_contract_wasm_update` that tries to update to an _invalid_ WASM and check that:
- [ ] The update fails
- [ ] The contract didn't get bricked in the process

Possibly try a few other forms of invalid-update besides just "the WASM was bad" (eg. auth failures or budget limits)

**Comment by dmkozh** [comment]
> Possibly try a few other forms of invalid-update besides just "the WASM was bad" (eg. auth failures or budget limits)

There is no auth for updating the Wasm (current contract updates its own Wasm, so it's an authorized action by default). I don't see much value in covering generic failures (like budget) for this specific case - any traps generically result in rollback, which includes the contract instance entry. We could cover `try_call` though, which hasn't been mentioned in this issue.
