### ISSUE TITLE
[test] type and argument checking on host function dispatch

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#1155]
- [ ] for each host function:
  - [ ] invoke with wrong-typed args should fail
  - [ ] invoke with wrong-number of args should fail
  - [ ] invoke with an unknown object handle should fail

**Comment by jayz22** [comment]
>  invoke with wrong-number of args should fail

I'm not sure how this can be done. The wasm code to call a function will have its type already encoded and will load the number of arguments based on the arity, so if we were to leave an extra (or one less) operand on the stack before `call` it would just make the wasm module invalid.
