### ISSUE TITLE
[test] rollback scenarios

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#1157]
Check that try_call failing (and rolling back) correctly rolls back:
  - [x] instance storage
  - [x] non-instance storage
  - [ ] host objects (if this is even supposed to happen? did we ever decide?)
  - [x] authorization state

**Comment by dmkozh** [comment]
Authorization state rollbacks are covered in `test_rollback_with_conditional_custom_account_auth`, `test_two_authorized_trees_with_rollback`, `test_rolled_back_auth_entry_can_be_reused`.

**Comment by sisuresh** [comment]
https://github.com/stellar/rs-soroban-env/pull/1177 added a test for instance and non-instance storage rollback.

**Comment by sisuresh** [comment]
@graydon we used to rollback host objects, but stopped that to allow for the diagnostic events to hold references to them. Did we discuss re-adding the rollback?

**Comment by dmkozh** [comment]
Given that host objects are immutable and also inaccessible for different contract calls, it doesn't seem like there is any observable/useful effect of the host object rollbacks.

**Comment by sisuresh** [comment]
In that case this issue should be done. @graydon do you agree?

**Comment by sisuresh** [comment]
Closing because we aren't going to rollback the host objects.
