### ISSUE TITLE
[test] storage misbehaviour tests

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#1159]
I'm not 100% sure these are missing but I think we could still use:
  - [ ] check that extending a temp entry fails (I think it's supposed to?)
  - [x] check writing large keys and values fails
  - [x] uploading large wasm fails
  - [x] uploading invalid wasm fails
  - [x] try extending an expired temp entry with the host function

**Comment by sisuresh** [comment]
> check that extending a temp entry fails (I think it's supposed to?)

This behavior is intentionally allowed based on what I remember from discussions (cc @SirTyson).

**Comment by SirTyson** [comment]
Yeah, restoring temp entries is not allowed, but extending via a host function or op is allowed. We did at one point have a proposal out for temp entries that could not be extended, but that was back in the rent balance era.

**Comment by sisuresh** [comment]
> Yeah, restoring temp entries is not allowed, but extending via a host function or op is allowed. We did at one point have a proposal out for temp entries that could not be extended, but that was back in the rent balance era.

We shouldn't be able to extend expired temp entries right? I don't think we have a test for this through the host function.

**Comment by SirTyson** [comment]
Correct. It looks like we have a test for the extend op, but not for the extend host functions. This would be a good one to add.

**Comment by sisuresh** [comment]
Hmm expired entries are not valid in the footprint, so a test for that doesn't make much sense.

**Comment by sisuresh** [comment]
"Try extending an expired temp entry with the host function" implemented in https://github.com/stellar/stellar-core/pull/4035/commits/6046c8e7b75a51670475684768036ca70bb9cd9b.
