### ISSUE TITLE
[test] bad invocations

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#1161]
Some patterns we should add to `test/invocation.rs`:
  - [x] cross-contract calls up to the default depth limit (100 frames) doesn't run out of Rust stack
  - [x] the above actually gets stopped _at_ the depth limit and doesn't go any further
  - [x] cross-contract `try_call` and indirect `try_call` both fail on unrecoverable errors
  - [ ] all failure tests work the same for both recoverable and non-recoverable errors from host functions as well as errors caused by guest code traps 

Also the existing cross-contract and indirect cross-contract call tests are a little hard to read. They are based on calling `vec_err` and `add` / `add_with` which are both sort of strange / nonobvious contracts. Might be good to reorganize and factor this set of tests. For example there is a test-wasm called ERR that just generates a variety of error types. Maybe consolidate around this (and extend it as needed, eg. with guest traps and both kinds of host function errors).

**Comment by dmkozh** [comment]
>  cross-contract calls up to the default depth limit (100 frames) doesn't run out of Rust stack

Covered in a few `test_deep_stack_...` tests.

**Comment by graydon** [comment]
To add detail to the last one:

1. Test calls host function `call`, which calls guest, guest calls some host function X, X fails with HostError, HostError turns into wasmi trap(HostError), propates through guest to return as `Err` in `call`, and `call` returns `Err` to test.
2. Same as 1 but `try_call` so test gets `Ok(Error)`
3. Same as 1 and 2 but with an unrecoverable error like out-of-gas, and `try_call` should therefore return `Err(HostError)`
4. Test calls host function `call`, which calls guest, guest _traps_ inside the VM (eg. executes `unreachable` instruction, or does divide-by-zero or something) and guest then returns `Err` to `call`, which returns `Err` to test.
5. Same as 4 but for `try_call` and getting `Ok(Err)`
6. Same as 4 and 5 but for running out of gas _in the guest_ so it's unrecoverable and `try_call` also gets `Err`
7. Test calls host function `call` which calls guest and guest just returns an Error itself, like a contract error, guest returns `Ok(ContractError)` to `call` and `call` returns `Err` to test
8. Same as 7 but with `try_call` and therefore getting `Ok(ContractError)` at the test level

I suspect if you want to try factoring this and using `crossroads` you might be able to factor it into 4 binary dimensions:
  - Recoverable vs. unrecoverable error
  - Propagating through wasmi as a Trap vs. an Error return
  - Originating in the VM vs. originating in a host function called by the guest
  - Invoking as `call` or `try_call`

**Comment by graydon** [comment]
(and maybe also for thoroughness "with debug mode flag turned on or off" to make sure the costs don't fluctuate)
