### ISSUE TITLE
[test] basic SAC tests

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#1166]
I am not 100% sure these are missing from the SAC tests but from my reading I think they might be:

- [x] Test that spending someone else's balance isn't allowed
- [x] Test that attempting to re-enter the SAC during a transfer (eg. via an auth hook) fails
- [x] Test that after a call _or_ a try_call that does a transfer and then fails, nothing was spent

**Comment by sisuresh** [comment]
I'm working on "Test that after a call or a try_call that does a transfer and then fails, nothing was spent".

**Comment by sisuresh** [comment]
For "Test that spending someone else's balance isn't allowed", this could mean either a  "transfer_from" where an allowance doesn't exist, or bypassing auth on a "transfer". The first is covered by the allowance tests, and then second should be covered in by [this](https://github.com/stellar/rs-soroban-env/blob/696d6f920b4b673e04cc01aeb09034ef2cdc15b8/soroban-env-host/src/test/stellar_asset_contract.rs#L1889-L1890) test.
