### ISSUE TITLE
[test] basic event tests 

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#1167]
The events system could use some more basic "kick it and see if it breaks" tests:
  
- [ ] very large event topics and data elements should fail
- [ ] logging lots of events in a loop should eventually fail
- [ ] expand the test for non-budget-observation of diagnostic logging to specifically call log_from_linear_memory from a contract
- [ ] use log_from_linear_memory from very large value, check that it fails
- [ ] test that when _errors occur_, having DEBUG on or off does not change the main observable budget

**Comment by jayz22** [comment]
The `hostile::excessive_logging` covers 3 and 4.

**Comment by jayz22** [comment]
1, 2, 5 are addressed in https://github.com/stellar/rs-soroban-env/pull/1189

**Comment by jayz22** [comment]
Resolved by above.
