### ISSUE TITLE
[test] extra auth tests

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#1169]
From the brainstorming-tests department, not totally sure auth tests don't already cover but I didn't see these:

- [x] everything structurally fine but cryptographically-invalid signature
- [x] interleaved trees: an invocation tree A->B->C->D where one auth is A->C and one is B->D (I think this should pass? maybe?)
- [x] calling `require_auth` for an account, and a custom-account contract, each of which doesn't exist
- [x] same but for other forms of dormancy (eg. one that's past its TTL, or perhaps otherwise disabled?)

**Comment by dmkozh** [comment]
> same but for other forms of dormancy (eg. one that's past its TTL, or perhaps otherwise disabled?)

Expired/archived entries shouldn't get to host, so this should be covered just once at storage level. Otherwise, I'm not aware of a way to explicitly disable accounts.

**Comment by dmkozh** [comment]
>  interleaved trees: an invocation tree A->B->C->D where one auth is A->C and one is B->D (I think this should pass? maybe?)

This shouldn't pass and is covered in several tests, such as `test_disjoint_tree_not_allowed`, `test_different_auth_trees_with_duplicate_addresses`, `test_two_authorized_trees` etc.

**Comment by dmkozh** [comment]
> everything structurally fine but cryptographically-invalid signature

This is covered in `test_auth_rejected_for_incorrect_payload` - I guess the question between incorrect signature/signer and incorrect payload is a bit philosophical, but the end result is the same (signature verification over expected payload fails).
