### ISSUE TITLE
`nom` v1.2.4 dependency won't be supported

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#1183]
### What version are you using?

4f4a7f3d

### What did you do?

Ran the tests.

### What did you expect to see?

Test stuff.

### What did you see instead?

```
warning: the following packages contain code that will be rejected by a future version of Rust: nom v1.2.4
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
```

**Comment by graydon** [comment]
This should have happened with #1208 -- please reopen if you see it resurface.
