### ISSUE TITLE
Replace use of &str in all string host fns with &[u8]

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#1188]
It appears that in the env host fns we're passing around references to guest-side strings as &str. However, I believe it would be more appropriate for us to change these to `&[u8]`.

Why:

The String type on Soroban is backed by bytes and there's no specification of any particular encoding.

It's possible for any external system to create a transaction that includes, as an input to a contract, bytes that are invalid utf8.

Because the SDK and the Env host fns require the use of &str when converting from a string on the contract side, it's impossible to guaranteed be able to round-trip a `String` value. If the input is invalid utf8, it can be given to a contract and extracted into a `&[u8]`, but there's no guarantee that the contract can convert it into a `&str` and then pass it back to the host. This is because the `str` type in Rust requires valid utf8.

**Comment by leighmcculloch** [comment]
cc @anupsdf I believe this is relatively important, and we should treat it like an interface bug.

**Comment by leighmcculloch** [comment]
Changes we should make:
- `string_new_from_slice` change `slice: &str` param to `slice: &[u8]`

**Comment by leighmcculloch** [comment]
Blocking:
- https://github.com/stellar/rs-soroban-sdk/issues/1138

**Comment by willemneal** [comment]
Why support non-utf8 strings?

**Comment by leighmcculloch** [comment]
> Why support non-utf8 strings?

If I recall correctly the main reason the String type was added so that when rendering Val's in places that are more appropriately rendered as a string, we can do so. Otherwise all Bytes would be always rendered as Bytes. (cc @graydon If you remember there was more to it than that?)

Whilst a specific encoding could be specified and that technically would make it easier to know how to render strings, rendering isn't anything that affects the protocol, so it seems unnecessary to introduce additional failure modes such as what to do if bytes aren't valid utf8. It also allows us to largely avoid the problem of converting strings from different languages into Soroban strings since different languages define strings differently.

**Comment by willemneal** [comment]
Yes but if a String is in the interface it makes downstream RPC clients then have determine what to do with a string of any encoding. Unicode is the standard and UTF-8 seems to be the biggest winner. We are already forcing clients to encode with XDR so I don't understand the friction in ensuring that the string is encoded in a standard way.

**Comment by leighmcculloch** [comment]
I think it'd be a good topic to raise in a new issue on the [rs-soroban-env] repo, or probably a good topic to take to [Discord]. The host's String type is already arbitrary bytes, and the host interface already exposes arbitrary bytes when converting from the host handle to a guest value as `&[u8]`. This issue is narrowly focused on fixing the asymmetry that exists in the host functions because when converting from guest value to host handle `&str` is unnecessarily required.

i.e. Today the SDK and environment support:

Input via XDR: `&[u8]`
Output via XDR: `&[u8]`
Converting from host to guest: `&[u8]`
Converting from guest to host: `&str`

This issue aims to:

Input via XDR: `&[u8]`
Output via XDR: `&[u8]`
Converting from host to guest: `&[u8]`
Converting from guest to host: `&[u8]`

[rs-soroban-env]: https://github.com/stellar/rs-soroban-env
[Discord]: https://discord.gg/stellardev
