### ISSUE TITLE
Cargo version pinning improvements

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#1222]
We're still not aggressive enough about making Cargo not change stuff underfoot. Plan:

 - [x] pass `--locked` to all cargo commands in every place we do anything in CI
 - [x] set all Cargo.toml version specs of our own to `=` constraints
 - [ ] add a make update-deps target that does `cargo +nightly -Z minimal-dependencies update` or so
 - [x] enable cackle and cargo-deny on core
 - [ ] update core's and env's deps using the same make update-deps and carefully compare solutions match
 - [ ] check that core and env both use cargo resolver v2

**Comment by graydon** [comment]
Not going to do all of this -- we'll do the parts that represent "locking what we've got" (steps 1, 2 and 4) but not adopt minimal-deps or change resolver or anything like that.

**Comment by leighmcculloch** [comment]
Why won't we change the resolver? It's a one line change.

**Comment by graydon** [comment]
Because it'd be weird / misleading to say we're on resolver 2 but not re-resolve with it, and the point here is to not change any more deps at this point.

**Comment by graydon** [comment]
Done all we're going to do here as of https://github.com/stellar/stellar-core/pull/4061 and https://github.com/stellar/rs-soroban-env/pull/1257
