### ISSUE TITLE
Expose imports in Host VM

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#128]
The Host VM exposes a list of exports which the CLI uses in its inspect sub-command. It would be useful if the Host VM could expose a list of imports which the CLI would use in its inspect sub-command.

**Comment by graydon** [comment]
Not sure what you mean here. The host VM imports from client wasm code only what it's asked to import in order to call. Do you want a list of exports-from-a-wasm?

**Comment by leighmcculloch** [comment]
The `Vm` already exposes the exports of the WASM, in the `functions` fn that I added here: https://github.com/stellar/rs-stellar-contract-env/blob/2310c1698e6869fa5ccc6afa8ea69fca7bf72cf5/stellar-contract-env-host/src/vm.rs#L230-L274.

I was hoping to also expose the imports of the WASM, the list of fns that the WASM expects to be present. If it's particularly troublesome to get we can live without it, but it might help with debugging if the stellar-contract-cli would output that list of imports when its `inspect` sub-command is used on a WASM file. [sjc](https://github.com/leighmcculloch/sjc) did this and so I was hoping to replicate that functionality.

**Comment by leighmcculloch** [comment]
Closing as we've gone long enough without this, without any consequence, which is signal that we don't need it as much as I thought we did.
