### ISSUE TITLE
Evaluate wasmi v0.32

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#1313]
Wasmi recently released [v0.32.0-beta.0](https://github.com/paritytech/wasmi/releases/tag/v0.32.0-beta.0) which contains new major features:
- the new register-machine bytecode based executor
- lazy Wasm function compilation.
- unchecked Wasm compilation.

This issue tracks the experimentation to use the new version in soroban-env, and accessing the performance impacts of various compilation/validation modes.

**Comment by jayz22** [comment]
I've pushed a new branch https://github.com/jayz22/wasmi/tree/parity-v32-beta containing necessary change to adapt stellar/wasmi into it. 

Here is the experimental soroban-env branch https://github.com/jayz22/rs-soroban-env/tree/explore-wasmi using it.

**Comment by graydon** [comment]
This was backed out before protocol 22. Will try again in subsequent protocols.
