### ISSUE TITLE
rpc: migrate libpreflight's fee computations to rs-soroban-env

### ISSUE THREAD

**Issue by 2opremio** [stellar/rs-soroban-env#1352]
The fees computed in RPC's `simulateTransaction` method are tightly coupled the host VM.

The disconnect between the RPC and rs-soroban-env in terms of fees has caused quite a lot of frustration in platform team.
The platform team doesn't take part in metering algorithm making it hard to update the fees algorithm in isolation from the Core team's decisions and code changes.

Migrating to rs-soroban-env  will also simplify adding integration tests to ensure preflighting doesn't diverge too much from Core's metering.

By migrating the [fee computations](https://github.com/stellar/soroban-tools/blob/v20.0.0-rc4/cmd/soroban-rpc/lib/preflight/src/fees.rs) to `rs-soroban-env` we hope to considerably improve the situation.

**Comment by dmkozh** [comment]
This is done now with https://github.com/stellar/soroban-rpc/pull/92
