### ISSUE TITLE
Pin `ed25519-dalek` for v22 Core release

### ISSUE THREAD

**Issue by dmkozh** [stellar/rs-soroban-env#1422]
We temporarily unpin the dalek version in order to unblock the downstream deps from updating to non-vulnerable version. We should pin this back after Core is updated to use new env for p22 or after v22 release (depending on whether unpinning works with prev+curr env build).

**Comment by sisuresh** [comment]
@dmkozh which version did we want to pin to?

**Comment by dmkozh** [comment]
I don't recall the exact version, but I suppose the latest one should work. Basically as long as cargo-deny doesn't complain we should be good.

**Comment by leighmcculloch** [comment]
Why do we need to repin? The lock file already pins the core build. And @graydon added a check to ensure that the env repo and core repos use the same version in the lock file. The unpinning was intended to be permanent.
