### ISSUE TITLE
Add host function for aborting current subtransaction with details / a status code

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#146]
~~We need a way for a contract to exit the subtransaction / call that it's currently running immediately, without popping / returning all the way back out to its outermost frame. The moral equivalent of the `exit(int)` standard library function in C.~~

~~Pass void for success, or a status for failure -- or just a status if we're going to keep the "ok" / "success" status code (this might be the exception to the "never pass a status" rule).~~

We should allow aborting the current subtransaction with _some_ details -- eg. calling `env.abort(status)` -- rather than just calling panic!(). This might include revising the status type to include a variant that denotes its file name / line number / a user-provided message as in #205.

**Comment by graydon** [comment]
I disagree with, but accept, the consensus-dislike of multiple success-exits (I think they're more useful than they cost).

I still think we need a fail-with-user-provided-details call. The `panic!()` calls in the existing contract are problematically uninformative to anyone trying to debug them.

**Comment by leighmcculloch** [comment]
> The `panic!()` calls in the existing contract are problematically uninformative to anyone trying to debug them.

They're informative when running locally in a debugger, but aren't useful after they've been compiled to wasm. 

Would there be a way to bundle other information into panic that isn't a string, such as a `Status`?

**Comment by leighmcculloch** [comment]
The main reason we started using a panic! instead of our own fns that trap was because the wasm unreachable fn isn't a const fn, but we can put panic! in const fns.

**Comment by graydon** [comment]
Yeah, in places we need it I understand. I just mean like reading through @jonjove's contract there are a bunch of logic-panics that will return a very opaque error to the user.

**Comment by leighmcculloch** [comment]
In the Rust std lib there exists `std::panic::panic_any`, which can be used to pass any value to the panic handler, even non-strings. This could be used to pass a `Status` that we surface somehow. But I can't find it in `core` even though https://github.com/rust-lang/rust/issues/78500 and https://github.com/rust-lang/rust/issues/80162 seem to indicate that panic should be identical between std and core 🤔.

**Comment by jonjove** [comment]
@graydon I haven't tried to do reasonable error reporting in the contracts I'm writing since error reporting is still in flux. I definitely don't want to give the impression that what's there is desirable to me.

**Comment by graydon** [comment]
We have (as of yesterday actually hooked-up) a way to _log_ an error. So we could _almost_ get away with a pure SDK-side `env.log(msg); panic!();` but it won't convey a status code to the caller. I think I want something a _tiny_ bit richer, like `env.fail_with_status(status)` so that the user code can say a handleable status that gets back to its caller. WDYT?

**Comment by leighmcculloch** [comment]
Hmm, how would this fit in with generating debug events? This looks like a different interface. We almost achieve the same thing with panic + Status returns, since a user contract could return a Status.

**Comment by graydon** [comment]
@jonjove now that you've done some work on making the token "native", does it make more sense to you to have a `abort_current_contract_with_status(Status)` function?

**Comment by jonjove** [comment]
Let's revisit that once I merge the native contract, so that everyone can see what is there.
