### ISSUE TITLE
Some WASM contracts in tests are missing instructions on how they are generated

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-env#152]
Some tests like `invoke_single_contract_function` have instructions on where to find the source code how to regenerate the WASM contract, but some other tests don't. This information should be filled in for every contract used in the test cases.

**Comment by jonjove** [comment]
Was this issue resolved when we added machinery to automatically regenerate test WASM? Like https://github.com/stellar/rs-soroban-env/blob/d6755cc1c2130dfea6e87c251dc9017e696a8cf5/Makefile#L20-L21

Or is there something more that needs to be done?

**Comment by leighmcculloch** [comment]
I think @graydon did the hard slog on moving all the tests into the test wasms workspace, so we should be able to close this. The only `include_bytes!` importing WASMs are in that workspace:
https://github.com/stellar/rs-soroban-env/blob/d87a381b82300e2b590a1ff29c86da49cfcc7e19/soroban-test-wasms/src/lib.rs#L45-L55
