### ISSUE TITLE
Clean up usage of `Hash` and `PublicKey`

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#157]
The current proposal in CAP-51 having both of them as object types, which provides guarantees on the correct length and provides conversions to and from binary. They exist in the xdr and in the code, but they aren't used and instead custom conversion code like [this](https://github.com/stellar/rs-stellar-contract-env/blob/main/stellar-contract-env-host/src/host.rs#L835) exists. 

There have been discussion of alternatives (e.g. see https://discord.com/channels/897514728459468821/979885313377845278/989628715417882654). 

The use of hash and public key should be migrated to the host object type or the alternative.

**Comment by leighmcculloch** [comment]
I think we should probably stick with using the `Binary` obj type for hashes at least. In regular application code hashing almost always results in a byte slice or byte array. For this case we probably don't need a type given the precedence.

I think we could do the same with the public key types. (Although, I acknowledge that the public key type is more fuzzy. Ed25519 keys are frequently represented as 32 bytes. If we ever support other key types they might not always be held in that format. It may be desirable to store some other key types in an uncompressed form, e.g. such as ecdsa keys, although that comes with safety concerns.)

**Comment by leighmcculloch** [comment]
@graydon @jayz22 Can we remove the public key and hash types? We still haven't found a need for them.

**Comment by graydon** [comment]
Sure, I guess. I still think punting to UDTs on these is a mistake and we should find a cheap way to do a tagged bytes object, but perhaps that falls under the aegis of "small-value optimization". @jayz22 could you take this, and remove Hash and PublicKey?
