### ISSUE TITLE
Type: BigInt: Validate our implementation of `BigInt` interops well with other ecosystems

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#171]
- [JS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt)
- [Java](https://docs.oracle.com/javase/7/docs/api/java/math/BigInteger.html)
- [Go](https://pkg.go.dev/math/big)
And add necessary host functions to facilitate that. 
[Ref](https://discord.com/channels/897514728459468821/992134825865662495/993931658740912178) to discord discussion.

**Comment by sisuresh** [comment]
No longer relevant because we [removed](https://github.com/stellar/rs-soroban-env/pull/581) BigInt support.
