### ISSUE TITLE
Support Native Contracts

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-env#175]
### What problem does your feature solve?

[CAP-54](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0054.md) describes a native contract, but we don't have any support for this yet.

### What would you like to see?

Support for native contracts.

### What alternatives are there?

None.

**Comment by leighmcculloch** [comment]
It would be beneficial if however this occurs the contract is 100% a valid non-native contract. i.e. It can be built to WASM and deployed and work, as well as be built to amd64 lib file that can be dynamically loaded by stellar-core.

The initial benefit of this is that someone can taken the token contract and make modifications. The longer term benefit is the ability to take contracts on chain and make them native.

**Comment by jonjove** [comment]
It's a bit complicated. There might be certain host functions that are only usable by native contracts, which makes native to WASM not guaranteed to work fully.

**Comment by jonjove** [comment]
Elevated access level. Specifically for the move to/from classic in CAP-0054.

**Comment by leighmcculloch** [comment]
This suggests to me that the move and to functions should be host functions.

**Comment by jonjove** [comment]
They will be: "There might be certain host functions that are only usable by native contracts". They just will only be callable by native contracts.

**Comment by leighmcculloch** [comment]
That's not what I meant. I mean that the functions of the token contract that are dependent on native only host functions, should probably by host functions themselves.

**Comment by jonjove** [comment]
I don't really think that's desirable. It means that we would have host functions specifically designed to interact with certain contracts. That seems very much like interactions going in the wrong direction.

**Comment by leighmcculloch** [comment]
>we would have host functions specifically designed to interact with certain contracts.

We would have host functions specifically designed to interact with certain contract APIs.

If we look at it from an outcomes perspective, it means the token contract would be forkable more completely, which is desirable.

Would the native-only host functions be constrained to move from/to? If so those parts of the contract could be behind a `nativeonly` feature I guess, so people could still fork and just ignore those components.
