### ISSUE TITLE
Type: Map: Add host fn to get a slice of a map given a start and end key

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#183]
To support converting an iterator into a Map, we need to be able to get a slice of a map in a similar way that we can get a slice of a Vec. The host fn should accept two keys, a low and a high, and return a map that has the elements between those two keys.

For Vecs range selection is start inclusive and end exclusive, but I assume for a Map it will need to be start inclusive and end inclusive.

**Comment by leighmcculloch** [comment]
cc @jayz22

**Comment by leighmcculloch** [comment]
This was done.

**Comment by jayz22** [comment]
Which PR was this done with? I don't see new map host functions. I also don't see any "slice" related functionality in the SDK.
Or is this issue about supporting iterators in maps in SDK?

**Comment by leighmcculloch** [comment]
This wasn't, sorry, I think I thought this was for Vec, but I see it was Map.

**Comment by leighmcculloch** [comment]
This got put into the July deliverables, but the SDK won't actually need this for July because I don't plan to circle back to use this fn until August. So @jayz22 if you don't need this in the July deliverable as a priority, it can be shifted.

**Comment by leighmcculloch** [comment]
I don't think we have a clear use case for slicing maps. I'm going to close. This functionality is purely additive, and can be added at any time that anyone identifies are use case.

Note that the original use case to support iteration, is no longer relevant.
