### ISSUE TITLE
Consolidate and Clean Host Function Exports

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-env#186]
### What problem does your feature solve?

Host function exports are split into many small, similar modules.

### What would you like to see?

Similar modules merged to make more efficient use of the available symbol space.

### What alternatives are there?

N/A

**Comment by graydon** [comment]
I don't think there's anything to do here anymore; perhaps there was earlier on. There are 10 modules and 93 host functions, grouped into modules of size 14, 10, 14, 19, 5, 2, 24, 2, 2, and 1 function. So some of them are small but .. there's no real risk of running out of of module symbol space, and we're not adding host functions or modules all that often anymore anyway.
