### ISSUE TITLE
Compile error if exported host functions overlap

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#189]
@jonjove reported in Discord ([ref](https://discord.com/channels/897514728459468821/995082726673744023)) that we had some extern host fns overlapping which he fixed in #185.

I double checked and tried changing functions to use the same link names and the Rust compiler doesn't error at all.

This seems like quite a footgun. Of course if this happens with functions that behave wildly differently we're likely to notice. But for functions that behave somewhat similarly this could go unnoticed but have an enormous impact.

The host functions are generated by some macro rules in the common crate. We should find some way to ensure that their names are all unique.

cc @jayz22 @graydon @jonjove

**Comment by leighmcculloch** [comment]
I don't love this idea, but a hack way to prevent this might be to write out some constants for each module and link name, since the compiler will error if there are constants with the same name. The error would not be particularly pretty, but any error is better than no error.

**Comment by anupsdf** [comment]
Setting target milestone to `Post testnet` after discussing with @graydon

**Comment by graydon** [comment]
since we use a proc macro now this is actually fairly trivial -- just check all the names when we read in the json file.
