### ISSUE TITLE
Small map optimization

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#200]
Currently the `im` library does a small-vector optimization, making small vecs up to 8 Vals use a single small 128 byte allocation with no substructure-sharing. It does _not_ do a similar optimization for small maps, so an empty map uses about 2700 bytes. We need to put in a small-map optimization too, probably using something simple like https://lib.rs/crates/vector-map or https://lib.rs/crates/sorted_vector_map or https://lib.rs/crates/litemap or whatever

**Comment by leighmcculloch** [comment]
Related to #196

**Comment by graydon** [comment]
No longer relevant, we're using dense sorted-vector maps exclusively now (and sized exactly to their content).
