### ISSUE TITLE
Cost models might be better with more than one input dimension

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#208]
Some cost models make more sense when viewed in terms of more than one independent variable (such as different sizes of separate inputs to a function that uses them both in a subtle way). Currently we funnel all inputs to cost models into a single input variable, and in many cases that might work (sum all input sizes, take the max of all input sizes, multiply one input size by another, etc.) but in other cases it might make more sense to treat the cost model as a function of separate input dimensions.

**Comment by jayz22** [comment]
Closing this as we have decided that all cost components should only dependent on single input.
