### ISSUE TITLE
Another round of host error classification

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#225]
Include new types since round 1 was done. 
- Bignum
- Map
- Metering

Under new infrastructure (https://github.com/stellar/rs-stellar-contract-env/issues/211) that splits the diagnostic details and error code.

**Comment by graydon** [comment]
As discussed in #673 we should enrich the error interface or change the actual calls to emit more debug events at error sites, since we're making the errors themselves corarser.

**Comment by jayz22** [comment]
Resolved with the error reform work mentioned above.
