### ISSUE TITLE
Clean up Symbol <-> ScVal errors

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-env#260]
Related to #259

**Comment by leighmcculloch** [comment]
@jonjove Could you elaborate to what this relates? The linked issue doesn't provide sufficient context.

**Comment by leighmcculloch** [comment]
@sisuresh Do you know what this relates to?

**Comment by sisuresh** [comment]
Looks like this issue tracks this [comment](https://github.com/stellar/rs-soroban-env/pull/259#discussion_r930170190) about using ConversionError instead of Error.
