### ISSUE TITLE
Contracts don't have constructors, which can lead to initialization being frontrun

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-env#265]
Let's take the [token contract ](https://github.com/stellar/rs-stellar-token-contract/blob/518638392f192f56e859e63e1b62c7294270995f/src/contract.rs#L57)as an example. Once the contract is deployed, `initialize` needs to be called to set the admin. If the user deploys the contract using a transaction with `InvokeHostFunctionOp`, then they must submit a second transaction to call `initialize`. It is possible for an attacker to sneak a transaction of their own in here where they call `initialize` and set admin to an account they control.

You can currently work around this by using a wrapper contract to deploy the token contract and call initialize in a single transaction, but the attack described above is still a foot-gun for an unaware user. We should discuss what we'd like to do here.

**Comment by leighmcculloch** [comment]
Can the two `InvokeHostFunctionOp` operations be embedded in the same transaction so they're atomic?

**Comment by sisuresh** [comment]
Yeah that's an option. [CAP-0052](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0052.md#external-interaction-with-a-smart-contract) currently specifies a limit of one `InvokeHostFunctionOp` per transaction, but that can be changed for this scenario.

**Comment by graydon** [comment]
Multiple invocations is probably the simplest, but we could also modify the `create_contract_*` paths to take a constructor name and/or argument vector and call a constructor / initializer function with it in the same transaction (or one with a standard name), if the former is too much of a footgun.

**Comment by graydon** [comment]
This feels like it's part of / connected to https://github.com/stellar/soroban-examples/issues/55 so putting in current iteration (since that one is)

**Comment by sisuresh** [comment]
Another thing we could do is update the operation so the create case has the parameters for the constructor. We might need to change how the footprint works here since we'd be calling into the host twice.

Something like
```
struct InvokeHostFunctionOp
{
    // The footprint for this invocation
    LedgerFootprint footprint;

    union switch (HostFunction type)
    {
    case HOST_FN_CALL:
        // Parameters to the call host function
        SCVec parameters;
    case HOST_FN_CREATE_CONTRACT:
        // Parameters to the create contract host function
        SCVec create_params;

        // Parameters to the call host function (Optional)
        SCVec* constructor_params;
    }
}
```

**Comment by sisuresh** [comment]
Recent discussion on [discord](https://discord.com/channels/897514728459468821/1067534037310255225/1067534499933593691) where constructors were requested. It sounds like even if we add multi-op support, a contract constructor that is guaranteed to have been executed before the contract can be used would be valuable.

**Comment by sisuresh** [comment]
Here's another [discord](https://discord.com/channels/897514728459468821/1062453421971623977/1062453421971623977) thread discussing multi invoke host operation transactions.

**Comment by sisuresh** [comment]
Here's a discussion on deploying and initializing a contract atomically without constructors - https://discord.com/channels/897514728459468821/1121532143051473057/1121532143051473057.

**Comment by dmkozh** [comment]
Any kinds of 'constructors' can be implemented now via 'factory' contracts. I don't think built-in constructors are necessary given that functionality, and they're are also bound to have more limitations than programmatic deployments. We may consider making a built-in deployer contract in the future though, but it would be a different issue.
