### ISSUE TITLE
Registering two contracts with same ID results in a HostUnknownError

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#293]

**Comment by graydon** [comment]
What would you like to happen? Just a clearer status?

**Comment by leighmcculloch** [comment]
An error is appropriate, a clearer error would be helpful.

**Comment by jonjove** [comment]
I threw in `HostUnknownError` because this isn't a real error (only occurs in tests) so I didn't know what was reasonable.

**Comment by jayz22** [comment]
Closing this issue. 
This will be covered by the broader effort of error classification. https://github.com/stellar/rs-soroban-env/issues/225
