### ISSUE TITLE
bigint_cmp returns RawVal instead of i64

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-env#314]

**Comment by jonjove** [comment]
Actually, why is there a `bigint_cmp` host function separate from the `obj_cmp` host function? What's the semantic difference here?

**Comment by leighmcculloch** [comment]
@jayz22 Do you know the answer to 👆 ?

**Comment by jayz22** [comment]
> 

@jonjove There is actually no semantic difference between the two. Underneath they both call `object.cmp`. So you are right. I will remove the `bigint_cmp` function.

**Comment by leighmcculloch** [comment]
We might like to remove it after https://github.com/stellar/rs-soroban-env/issues/329, since removing it will require bumping the env interface version, which means rebuilding all the examples, which will be easier once all the test vectors are in this repo.
