### ISSUE TITLE
Add host functions to support token wrapper interface

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-env#316]
Related to https://github.com/stellar/soroban-token-contract/issues/5 and #175

**Comment by leighmcculloch** [comment]
@jonjove Which host fns exactly need adding for this?

**Comment by jonjove** [comment]
@leighmcculloch I already implemented them in #338 (draft), although they are ugly and untested. See https://github.com/stellar/rs-soroban-env/blob/0528987f0985f7c45fbb91fa39e48a0731864699/soroban-env-host/src/host.rs#L698-L810
It turns out I didn't implement them exactly as host functions because it occurred to me that they don't actually need to be exported to WASM (since they can't be used in that context).
