### ISSUE TITLE
Type: Vec: Add fns first_index_of, last_index_of, binary_search

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#317]
Add a `vec_first_index_of` host function that accepts a `Vec`, and a `RawVal`, and returns a u32 of the first index indicating if the `Vec` contains the value.

Add a `vec_last_index_of` host function that accepts a `Vec`, and a `RawVal`, and returns a u32 of the last index indicating if the `Vec` contains the value.

Add a `vec_binary_search` host function that accepts a `Vec` assumed to be sorted, and a `RawVal`, and returns a u32 index of the value in the `Vec`. If the item cannot be found, returns a u32 of the index of where the value could be inserted. Unclear how we should distinguish these two u32 values, maybe they should be high/low of a u64. (cc @graydon)

cc @jayz22

**Comment by jayz22** [comment]
> Unclear how we should distinguish these two u32 values, maybe they should be high/low of a u64. (cc @graydon)

I like this idea, however, we can't disambiguate the `u64::ZERO` (`0u32|0u32` ) case with this approach. 
I'm going to go with a tuple of  `(RawVal, RawVal)` as the return type, where one of them will be a `Static::Void` and the other one contains the index. I.e.:

```
match res => {
(idx, Status::Void) => !todo() // "found value at idx"
(Status::Void, idx) => !todo() // "not found, correct place to insert is idx"
}
```

**Comment by leighmcculloch** [comment]
The tuple will require a Vec and a lot more instructgions on the wasm side.

How about we make the return value positive if found, negative if not found?

**Comment by leighmcculloch** [comment]
Oh right, as you say, can't disambiguate zero.

**Comment by leighmcculloch** [comment]
Wait, how about we use high low in a different way?

The low can always be the index. The high can be 0x0 if found, and 0x1 if not.

**Comment by jayz22** [comment]
Ah yes, that can work!
