### ISSUE TITLE
Finish the contract_event / system_event host functions

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#322]
These host functions currently don't do anything -- they're `todo!()` -- and there's an empty stub in `events.rs` for the `ContractEvent` type. This all needs to be filled in so that the CLI and host embedding can report events to their callers.

**Comment by graydon** [comment]
cc @jayz22 as you might want to take this also? I'll do it if you do not want it or are too busy.

**Comment by jayz22** [comment]
Sure I'm happy to take it. Although, I probably won't make concrete progress on it until later next week as I'm currently still occupied by the budget metering.
