### ISSUE TITLE
Meta interface comment should match code

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-env#328]
### What problem does your feature solve?

The comment in this file describes functionality that doesn't exist.

### What would you like to see?

The comment and functionality should match.

### What alternatives are there?

N/A

**Comment by leighmcculloch** [comment]
Which comment does this issue refer to?

**Comment by graydon** [comment]
The meta.rs file is the place the contract declares its interface -- it will never be a range, only a specific interface version it was compiled against.

You're looking for https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/vm.rs#L165 which is the host-side code that checks to see if it supports the contract interface version. You're right that at the moment it's checking a "range" of values with a single point, but the broader point (as the comment discusses) is that any hard-wired interface version range would be wrong anyways -- the final state, once we declare backward compatibility, will be an ever-expanding _on chain_ range, stored as a config value and subject to upgrades; none of which we have working yet.

I .. can post a change that makes this a _bit_ more obvious / explains in a bit more detail (or less? is it too verbose?) but the comment does describe both where we're at and where we're going, and where we're going requires functionality that's not done yet, so ..
