### ISSUE TITLE
Tests should create contracts with host functions

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-env#334]
### What problem does your feature solve?

Tests currently create contracts by directly manipulating ledger state instead of using the appropriate host functions. For example

https://github.com/stellar/rs-soroban-env/blob/db1b4764fec63844677ba2ebc3c1305ff4e0c229/soroban-env-host/src/test/util.rs#L60-L78

### What would you like to see?

Tests should create contracts by using appropriate host functions.

### What alternatives are there?

TODO

**Comment by sisuresh** [comment]
Closing because we now use `invoke_function` to create contracts in tests - https://github.com/stellar/rs-soroban-env/blob/d803b0922d1d9eb4d3cfde5e6d574c7776c23388/soroban-env-host/src/test/util.rs#L161.
