### ISSUE TITLE
Expose types from native contracts

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-env#335]
See https://github.com/stellar/soroban-examples/pull/62#discussion_r946015347

**Comment by sisuresh** [comment]
Closed by https://github.com/stellar/rs-soroban-sdk/pull/686

**Comment by leighmcculloch** [comment]
This will need redoing every time we change the token contract. We need a way to remind us of that. Maybe a test in the soroban-token-spec that calls every function once would suffice?
