### ISSUE TITLE
Should vec_push_front / vec_pop_front host functions exist?

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-env#341]
These functions don't exist right now, but are actually as efficient as `vec_push_back` / `vec_pop_back` in `im_rc`. For context, see [`im_rc::Vector::push_front`](https://docs.rs/im-rc/latest/im_rc/struct.Vector.html#method.push_front).

**Comment by leighmcculloch** [comment]
If they're efficient yup. +1

**Comment by jayz22** [comment]
+1. I can add these.
