### ISSUE TITLE
`system_event` does not work from within `HostFunction` context

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#345]
`system_event` is an internal host function that is meant to be called from within host functions to log system-level events related to a contract ([ref](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0056.md#different-event-types)). 
However, calling it from a host function means the path is shared by both being invoked from a contract (including test contracts) and being invoked from core. 
This will fail if invoked from core (`Frame::HostFunction`) since there is no valid contract ID. 
Should we add a `DummyContractId` (e.g. `[0; 32]`) and return it from `get_current_contract_id()` if context is `HostFunction`? 
Or should we skip `system_event` call if called within `HostFunction` context?

**Comment by jayz22** [comment]
cc @sisuresh

**Comment by graydon** [comment]
I think we should emit events in that case, and either use a sentinel `[0;32]`-like value or make the contract ID in the event optional. Don't really care which; whatever we do I suspect it should match the broader (not super deep) design choice about how we represent the no-contract-ID context in general. I'm not sure we have a consistent story for that presently (eg. `get_current_contract` fails in the no-contract-ID context, but maybe it'd be better to return a sentinel value?)

**Comment by jonjove** [comment]
I'm generally opposed to magic sentinel values, so if it's possible to avoid that then I would appreciate it.

**Comment by sisuresh** [comment]
I think an optional ContractID is fine and we can add a comment in the xdr that explains the null scenario.

**Comment by leighmcculloch** [comment]
> calling it from a host function means the path is shared by both being invoked from a contract (including test contracts) and being invoked from core.

Why does core call `system_event`? Maybe it shouldn't. It sounds like system events have dual purpose. They are emitted by teh system in relation to contract actions, and emitted by the system for other reasons. That other reasons case should probably be a different type of event.

**Comment by sisuresh** [comment]
I'm not sure if they're dual purpose. The difference is that some host functions can be called directly by core - 
1. Core calls `create_contract_from_ed25519`, which can emit the contract_id of the new contract.
2. A contract calls `create_contract_from_contract`, which can also emit the contract_id of the new contract.

I don't think it makes sense to use different event functions or types here.

**Comment by graydon** [comment]
I think this is done now -- the contract ID is optional and will be empty when running in a `HostFunction` context.
