### ISSUE TITLE
Symbol::from_str error should be clearer

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-env#346]
If a user defines the struct below, the error you see at the bottom is what you would get during compilation. The issue here is that `contract_id` is greater than 10 characters, but the error doesn't mention this. `from_str` is aware of the `SymbolError::TooLong` and `SymbolError::BadChar` errors, so that information should be in the error.

We could also allow member names to be longer than 10 characters, but that should be discussed first.

```
#[derive(Clone)]
#[contracttype]
pub struct Custom {
    pub contract_id: BytesN<32>
}
```

Error - 
```
/cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/7395b81/soroban-env-common/src/symbol.rs:145:23
    |
145 |             Err(_) => panic!(),
    |                       ^^^^^^^^
    |                       |
    |                       the evaluated program panicked at 'explicit panic', 
/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/7395b81/soroban-env-common/src/symbol.rs:145:23
    |                       inside `soroban_sdk::Symbol::from_str` at /rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/panic.rs:50:9

```

**Comment by leighmcculloch** [comment]
There's a few aspects to this:
- `Symbol::from_str`'s panic error message should be clearer, as you note above.
- `SymbolError` should implement `Display`.
- `contracttype` should render these messages as a compile error, not as a panic.
