### ISSUE TITLE
Creating contracts "from contract" and "from ed25519" with "salt" is not intuitive

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#348]
> > The distinction between creating a contract from an ed25519 or a contract is not particularly relevant within the SDK. Contracts can only create contracts from contracts.
> 
> I see the confusion here, but this logic is not correct. A contract can create a contract from an ed25519 if the ed25519 signature is passed to the contract as input. This functionality is actually a simple way to prevent ID-sniping in https://github.com/stellar/soroban-examples/issues/55. I'm not opposed to a rename, but this rename probably isn't the right one because it's unclear how the other variant would coexist.
> 
> This PR also suggests that we probably aren't doing a good enough job explaining how existing functionality can be used. Maybe we should enumerate different possible scenarios and describe how the functions should be used in those scenarios. It's plausible this scheme can even be simplified... we came up with this quite early in the design process.

_Originally posted by @jonjove in https://github.com/stellar/rs-soroban-sdk/issues/454#issuecomment-1219540835_

> +1
> 
> > This PR also suggests that we probably aren't doing a good enough job explaining how existing functionality can be used.
> 
> I think it goes deeper than a missing explanation. The way that we are framing contract creation irrespective of documentation is not intuitive.
> 
> For example, the terms `_from_contract` and `_from_ed25519` are confusing. It is easy to arrive at multiple definitions for what it can mean to be "from" one of these things. When using an ed25519 public key to create, you point out that we can create "with ed25519 from a contract," so the "from contract" applies to both.
> 
> The term `salt` is also ambiguous. While I agree we are technically using the term correctly, it isn't intuitive, and its name doesn't communicate important properties of its value, such as its uniqueness in the scope of the contract or ed25519.
> 
> I think we need to find some better term to define the "identifier", or "sub-identifier", which is currently the "salt". And a better term to define the "scope" of uniqueness that the identifier applies within, which is either a contract or an ed25519.

_Originally posted by @leighmcculloch in https://github.com/stellar/rs-soroban-sdk/pull/454#issuecomment-1220221873_

@jonjove @sisuresh @tomerweller

**Comment by leighmcculloch** [comment]
I've marked this issue as `🚨 Critical` and put it in the `August` deliverable, because it feels like we need to address this to make the deployment of contracts accessible.

**Comment by jonjove** [comment]
The bad news: I don't see--at least right now under current design assumptions--any way that we can remove any of this functionality. The good news: that makes this problem a relatively simpler one of finding a better way to express the concepts.

With that in mind, I think there are a few steps that we should follow to get this cleaned up:

1. Agree on how to succinctly describe the behavior of these functions
2. Agree on how to present them as host functions
3. Agree on how to present them in the SDK

I'm going to make proposals for all 3 steps, but this is really me looking for feedback (@leighmcculloch @sisuresh). I'm not going to pretend that I really like what I've proposed here. But I'm acknowledging the shortcomings with our current design, and trying to start moving towards something more comprehensible.

### Describe the behavior

The function currently known as `create_contract_from_contract` creates a contract and includes the contract ID in the domain separator. The function currently known as `create_contract_from_ed25519` checks for a valid signature, then creates a contract and includes the ed25519 public key in the domain separator. The descriptions are analogous for creating native contracts.

### Host functions

Given the emphasis on the domain separator in the above description, the host function names should probably emphasize that

```rust
fn deploy_wasm_contract_with_contract_domain(
    bytecode: Object,             // Bytes
    salt: Object,                 // Bytes
);

fn deploy_token_contract_with_contract_domain(
    salt: Object,                 // Bytes
);

fn deploy_wasm_contract_with_ed25519_domain(
    bytecode: Object,             // Bytes
    salt: Object,                 // Bytes
    public_key: Object,           // BytesN<32>
    signature: Object,            // BytesN<64>
);

fn deploy_token_contract_with_ed25519_domain(
    salt: Object,                 // Bytes
    public_key: Object,           // BytesN<32>
    signature: Object,            // BytesN<64>
);
```

### SDK

We would add a few helper types (analogous to `Account` or `ContractData`) in `mod contract_deployer` 

```rust
pub struct SelfDomain(Env);

impl SelfDomain {
    pub fn deploy_wasm(bytecode: Bytes, salt: Bytes) -> BytesN<32>;

    pub fn deploy_token(salt: Bytes) -> BytesN<32>;

    // These functions are theoretical but could be useful if one wants to know the ID without deploying
    pub fn wasm_id_from_salt(salt: Bytes) -> BytesN<32>;
    pub fn token_id_from_salt(salt: Bytes) -> BytesN<32>;
}

pub struct Ed25519Domain(BytesN<32>);

impl Ed25519Domain {
    pub fn deploy_wasm(bytecode: Bytes, salt: Bytes, signature: BytesN<64>) -> BytesN<32>;

    pub fn deploy_token(salt: Bytes) -> BytesN<32>;

    // These functions are theoretical but could be useful if one wants to know the ID without deploying
    pub fn wasm_id_from_salt(salt: Bytes) -> BytesN<32>;
    pub fn token_id_from_salt(salt: Bytes) -> BytesN<32>;
}

pub struct ContractDomain(BytesN<32>);

impl ContractDomain {
    // Can't deploy in this configuration

    // These functions are theoretical but could be useful if one wants to know the ID without deploying
    pub fn wasm_id_from_salt(salt: Bytes) -> BytesN<32>;
    pub fn token_id_from_salt(salt: Bytes) -> BytesN<32>;
}
```

Then we could either add helper functions (along the lines of `account` and `contract_data`) to `Env`, or just let people construct these directly.

**Comment by leighmcculloch** [comment]
I think goes a long way to improving things.

Could we use the term `namespace` instead of `domain`? I think it might have less ambiguity because of the main other places the word domain shows up in engineering / technical things, where-as namespacing almost always refers to specifying some context.

+1 to adding the types that contain Env. Can we structure them as:

```rust
impl Env {
    pub fn deploy(namespace: N) -> Deploy<N>;
}
```

```rust
pub struct Deploy<N: Namespace>(Env, N);

impl Deploy {
    pub fn wasm() -> DeployWasm;
    pub fn token() -> DeployToken;
}
```

```rust
pub struct DeployWasm<N>(Env, N);

impl DeployWasm<N> {
    pub fn id(salt: BytesN) -> BytesN<32>;
    pub fn deploy(salt: BytesN, wasm: Bytes) -> BytesN<32>;
}
```

```rust
pub struct DeployToken(Env, N);

impl DeployToken {
    pub fn id(salt: BytesN) -> BytesN<32>;
    pub fn deploy(salt: BytesN) -> BytesN<32>;
}
```

```rust
pub trait Namespace {
    pub fn components() -> Vec<RawVal>;
}

pub struct Ed25519Namespace {
    pub public_key: BytesN<32>,
};

impl Namespace for Ed25519Namespace {
    // ...
}

pub struct ContractNamespace;

impl Namespace for ContractNamespace {
    // ...
}
```

**Comment by leighmcculloch** [comment]
An example of using the above would be:

```rust
env.deploy(ContractNamespace).wasm().deploy(salt_bytes, wasm_bytes)
```

**Comment by leighmcculloch** [comment]
We could also simplify the above to something with less parts, like:
```rust
env.deploy(ContractNamespace).wasm(salt_bytes, wasm_bytes)
```
Or
```rust
env.deploy_wasm(ContractNamespace, salt_bytes, wasm_bytes)
```

**Comment by jonjove** [comment]
> Could we use the term namespace instead of domain?
It's funny you suggest this because I originally had namespace everywhere and changed it. I switched to domain because namespace suggests to me that names have a hierarchical structure `a::b`. But that's a weak association. Really, I'm happy either way so let's go with namespace.

I'm slightly concerned about `env.deploy(...).wasm().deploy(...)` because the first deploy actually doesn't do anything and this could confuse people. Would you be open to something like 
```rust
env.make_deployer(ContractNamespace).wasm().deploy(salt_bytes, wasm_bytes)
``` 
instead? I have a slight preference because `make_deployer` doesn't sound like it will actually create your contract. Another version of this that I think could be reasonable, similar to your first example, is
```rust
env.make_deployer(ContractNamespace).wasm(wasm_bytes).deploy(salt_bytes)
env.make_deployer(ContractNamespace).token().deploy(salt_bytes)
```
which I like because it creates this notion of many things that can be deployed using a uniform `deploy` function (could even be a trait `Deployable` in this case).

The last version you shared `deploy_wasm(ContractNamespace, ...` is also quite appealing to me because it's both compact and pretty obvious what it means.

Overall, I'm not to fussy about the variant we choose. I feel a little bit like I'm splitting hairs because all of these seem so much better than the current interface.

**Comment by jonjove** [comment]
Actually, never mind about my other reasonable idea. It's not actually reasonable.
```rust
env.make_deployer(ContractNamespace).wasm(wasm_bytes).id(salt_bytes)
```
doesn't work great... you shouldn't need the `wasm_bytes`.

My vote is either for 
```rust
env.make_deployer(ContractNamespace).wasm().deploy(salt_bytes, wasm_bytes)
```
or
```rust
env.deploy_wasm(ContractNamespace, salt_bytes, wasm_bytes)
```
@sisuresh any thoughts?

**Comment by leighmcculloch** [comment]
I'm leaning to a small change to one of your suggestions, remove the `make_`:
```rust
env.deployer(ContractNamespace).wasm().deploy(salt_bytes
```

**Comment by jonjove** [comment]
Great, I'm happy with it.

**Comment by sisuresh** [comment]
The new host function names are much more intuitive.

Personally, I'd go with something like what you proposed initially (`SelfDomain` and `Ed25519Domain` but with namespace instead of domain) as the only way to create contracts. I think that interface would be easier to understand for someone looking at the sdk for the first time.

**Comment by sisuresh** [comment]
I don't have an issue with your suggestion though. Definitely an improvment to what we have today.

```rust
env.deployer(ContractNamespace).wasm().deploy(salt_bytes, wasm_bytes)
```

**Comment by leighmcculloch** [comment]
> I'd go with something like what you proposed initially (`SelfDomain` and `Ed25519Domain` but with namespace instead of domain)

Could you provide an example of what the call a developer would make so that we can compare it with https://github.com/stellar/rs-soroban-env/issues/348#issuecomment-1228968047?

**Comment by sisuresh** [comment]
Something like
```rust 
env.contract_namespace().deploy_wasm(wasm_bytes, salt_bytes) 

env.ed25519_namespace().deploy_wasm(wasm_bytes, salt_bytes, sig_bytes) 
```

**Comment by leighmcculloch** [comment]
There's also the case that someone might want to create the ID of another contracts deployed contract. So we actually have three namespaces:

```rust
SelfNamespace
ContractNamespace { contract_id }
Ed25519Namespace { public_key }
```

**Comment by leighmcculloch** [comment]
I'm inclined to use an enum or type for each namespace because it'll feel more natural to map from other enums into an enum than it is to map to functions.

To your point though the extra layer of .wasm() is probably unnecessary. 

```rust
env.deployer(namespace, salt_bytes).deploy_wasm(wasm_bytes)
```
```rust
env.deployer(namespace, salt_bytes).deploy_token()
```
```rust
env.contract_id(namespace, salt_bytes)
```

Where we define three namespaces structs and two namespace enums. 

Structs:
```rust
struct SelfNamespace
struct ContractNamespace { contract_id }
struct Ed25519Namespace { public_key }
```

Enums:
```rust
enum DeployerNamspace { Self, Ed25519 }
enum IdNamspace { Self, Contract, Ed25519 }
```

And the structs can be into convertible into the enums.

**Comment by leighmcculloch** [comment]
I did a quick spike of something like ☝🏻 in https://github.com/stellar/rs-soroban-env/issues/348. I'm not attached to it and fine to discard if the interface is not good from your perspective @sisuresh @jonjove. The main part to look at is the user perspective here:

```rust
#![no_std]
use soroban_sdk::{contractimpl, Bytes, BytesN, CurrentNamespace, Env};

pub struct Contract;

#[contractimpl]
impl Contract {
    pub fn create(e: Env, c: Bytes, s: BytesN<32>) {
        let _contract_id = e.contract_id(CurrentNamespace, &s);
        let _contract_id = e.deployer(CurrentNamespace).deploy_wasm(&s, c);
    }
}
```

Ref: https://github.com/stellar/rs-soroban-sdk/pull/503/files#diff-313b548312a7889d34e3fca9a0c2c76b0e7eed7467013406c0109dad8780bf44

**Comment by jonjove** [comment]
I think what you did overall is good, but the loss of `wasm` / `token` is probably not desirable. You can't get the contract id without knowing if a contract is wasm or a token (this is required to get deterministic-unique contract IDs for classic asset wrappers, see `ENVELOPE_TYPE_CONTRACT_ID_FROM_ASSET` in [CAP-54](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0054.md#xdr-changes)). So `e.contract_id(...)` is misleading, because it doesn't include the information about what kind of contract--a version that handles this correctly was demonstrated in your earlier post https://github.com/stellar/rs-soroban-env/issues/348#issuecomment-1228936983. 

That being said, I was thinking over the weekend that the way we were using `wasm` / `token` was a bit clunky and that the salt was appearing in an unintuitive place. How would you feel if your example looked like

```rust
#[contractimpl]
impl Contract {
    pub fn create(e: Env, wasm: Bytes, salt: BytesN<32>) {
        let _contract_id = e.contract_id(CurrentNamespace, &salt);
        let _contract_id = e.wasm_deployer(CurrentNamespace, &salt).deploy(&wasm);

        let public_key = BytesN::from_array(&e, &[0; 32]);
        let signature = BytesN::from_array(&e, &[0; 64]);
        let namespace = Ed25519Namespace { public_key };
        let _contract_id = e.wasm_deployer(&namespace, &salt).contract_id();
        let _contract_id = e.wasm_deployer(&namespace, &salt).deploy(&wasm);
    }
}
```

Why do I like this version? The "deployer" gets all the information to construct the ID which makes sense because that's what the `deployer` is for. `deploy` just gets the additional information needed to actually create the contract, and `contract_id` needs no additional information. This handles `contract_id` generation correctly. And it's relatively compact, while still being clearly readable (it's obvious to me what `wasm_deployer` or `token_deployer` should do).

**Comment by leighmcculloch** [comment]
The reason I left salt out of the deployer function signature is because any arguments we add to that signature are required across all namespaces. If we wanted salt to be part of choosing a deployer we should put it inside the namespace, and maybe rename Namespace to something else to indicate it captures all the inputs that define what an ID is.

**Comment by jonjove** [comment]
> any arguments we add to that signature are required across all namespaces

Great point.
