### ISSUE TITLE
Add invoke contract function that indicates if reentry is allowed

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#362]
We discussed in an open protocol meeting months ago about ideas for how to lessen the chances of footguns with surprise reentry. One of the simple ideas we discussed, and I think most people were okay with, was to require the invoker of a contract from within a contract to indicate if they were okay with reentry or not.

**Comment by jonjove** [comment]
I only found https://github.com/stellar/rs-soroban-env/issues/336 after you opened this issue, but I think this might be duplicate.
