### ISSUE TITLE
create_contract_from_ed25519 and create_contract_from_contract: Bytes vs. ContractCode

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#369]
The functions create_contract_from_ed25519 and create_contract_from_contract take a WASM-containing Bytes (formerly "Binary") input and produces / stores a WASM-containing ContractCode. This is a bit weird, and possibly not intended? I suspect it's residual from when it returned a Binary. It should be sorted out before we finalize this interface.

**Comment by leighmcculloch** [comment]
Fwiw the interface we have to creating contracts via these two functions is not intuitive and I think we need to revisit it and reframe it. There's a separate issue for that here: https://github.com/stellar/rs-soroban-env/issues/348.

**Comment by leighmcculloch** [comment]
Fyi the SDK has no "ContractCode" type, and it isn't really valuable for us to add it or maintain that type in the SDK, so it'd be great if the SDK can keep creating contracts just from wasm. We can add it if we need to buy really the SDK just needs to deploy a blob of wasm.

**Comment by jonjove** [comment]
Totally agreed with @leighmcculloch, I do not believe users should ever encounter `ContractCode`. The interface provided is what I intended. I'm closing this since the bigger picture of what creating contracts should look like will be handled in #348.
