### ISSUE TITLE
Env functions like contract data don't work outside of an invocation

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#396]
Initially most of the Env functions like reading contract data worked inside tests, because there was no permission restrictions about what could be accessed by who. This was good for tests because you could write a test that invoked a contract in some ways, and then in the test you could assert on contract data having been stored.

It seems this has changed, and it is no longer possible to read contract data in a test after an invocation. We currently have no way to read the ledger directly because we were relying on the ability to read contract data inside the test.

We probably need to revisit the idea of letting contracts access the underlying ledger data, or at the least, pretending to be inside an invoked contract and being able to do all the things that contract is allowed to do, something like:

```rust
env.as_contract(&contract_id, |env| {
    let val = env.contract_data().get(...);
    // ...
    env.deployer().from_contract(salt).deploy(WASM);
    // ...
})
```

This issue is similar to the issue described in https://github.com/stellar/rs-soroban-sdk/issues/530#issuecomment-1231900908 where deployment of contracts cannot happen outside of an invocation either.

cc @jonjove @graydon @sisuresh

**Comment by leighmcculloch** [comment]
I see two solutions for this:

1. Rely purely on view-style functions in contracts to inspect the state. This can be done today, and is relatively sane I think.

3. Otherwise, I think a solution to this is to create testutils functions for all these types of functions, that use the host to get at things like contract data with contract ID being a parameter. So you don't need to be in a contract to use them, but you can reach into any contract you've registered. This would look something like:

   ```rust
   env.testutils().contract_data().get(contract_id, key)
   ```

**Comment by leighmcculloch** [comment]
The pattern I'm using for events and logging is to defined a trait in `testutils` that the main object implements, so the testutils logic is in the same place as the other logic, but it is only available when the trait is included in tests.

For example:

This is the logic for publishing events in contract code:
```rust
env.events().publish((topic1, topic2), data)
```

This is the logic for getting all events published, which you can only do in tests:
```rust
use soroban_sdk::testutils::Events;
env.events().all()
```

So if we added anything for testutils to do with contract data, I think it would look like this:

The logic in contract code:
```rust
env.contract_data().get(key)
```

The logic in tests:
```rust
use soroban_sdk::testutils::ContractData;
env.contract_data().for(contract_id).get(key)
```

**Comment by graydon** [comment]
I'm afraid I don't understand this issue issue. You say:

> It seems this has changed, and it is no longer possible to read contract data in a test after an invocation

I don't know what this is referring to. Can you describe some code, what it used to do, and what it now does more concretely?

**Comment by leighmcculloch** [comment]
Early on I thought we were able to read data out of the Env, because it became scoped by contract ID. I might be remembering back to an early prototype.

The fact it is scoped by contract ID isn't bad, that's how it should work.

This issue is just about figuring out what the right way for a contract developer to write assertions on contract data in a test.

I am personally a fan of outside-in testing, and so if I was writing tests I'm fine with what we have today: I'd add contract functions that expose the contract data and make them part of the API.

I know a lot of people prefer to test the internals though.

The only way a developer has to test the internal contract data values of a contract in a test is to add contract fns that expose the data, and then use them in the test. They could even put those contract fns gated on a `#[cfg(test)]` so they don't get exposed when deployed. I guess that's a fine story and we don't need extra functions? Wdyt?

**Comment by leighmcculloch** [comment]
I added support for attributes on contractimpl fns in https://github.com/stellar/rs-soroban-sdk/pull/651 because I wanted to use it in a test vector, and as it happens, I think it does sufficiently address this issue.
