### ISSUE TITLE
Precompiled Contracts on the host env

### ISSUE THREAD

**Issue by heytdep** [stellar/rs-soroban-env#406]
### What problem does your feature solve?
Is there yet any thought on precompiled contracts? For example, elliptic curve pairings or elliptic curve multiplication/addition are inefficient or difficult to implement on the EVM, so Ethereum directly implements the contract in Go (https://github.com/ethereum/go-ethereum/blob/master/core/vm/contracts.go#L504), which is also more safe and efficient since it can directly rely on existing and optimized implementations like bn256 (https://pkg.go.dev/golang.org/x/crypto/bn256).

### What would you like to see?
Allowing for some contract functions to be pre-compiled into the network and can be called by a contract, for example in solidity I can call the following code to perform BN256 pairing by calling this go function: https://github.com/ethereum/go-ethereum/blob/master/core/vm/contracts.go#L504

```solidity
assembly {
            success := staticcall(sub(gas(), 2000), 8, add(input, 0x20), mul(inputSize, 0x20), out, 0x20)
            // Use "invalid" to make gas estimation work
            switch success case 0 { invalid() }
        }
```

Is this something that is somewhat compatible with Soroban’s host environment?

**Comment by heytdep** [comment]
@leighmcculloch Does this mean that the token contract has a different execution VM and can use external crates for example while running on the host environment?

**Comment by leighmcculloch** [comment]
cc @graydon @jonjove

**Comment by graydon** [comment]
@heytdep there are two different things here with somewhat different semantics. 

1. Simple host functions, which are probably the best bet for things like elliptic curve operations. These are compiled to native code, can use any rust libraries we're comfortable adding to the host, and can be very cheaply called from any contract. We already provide a bunch of host functions and will definitely be providing more (especially cryptographic ones) over time. The whole design of Soroban rests heavily on having a large repertoire of useful host functions.
2. Full built-in _contracts_ which have some larger quantity of the machinery that a wasm contract would have (eg. an identifier that can serve as the target of the call operation, conformance to a standard interface such as that for tokens) but are still compiled to native code and linked into the host. We're providing some of these, but they're a less-general tool, and involve a bit more machinery than a simple function.

**Comment by heytdep** [comment]
@graydon that sounds like an optimal design. I was already implementing EC operations with soroban types but given that we'll have more optimized host functions I guess I'll stop 😅. 

Thanks for the clarification, happy to give any insight on EC ops crates when its time to start extending the host functions.
