### ISSUE TITLE
Test native token wrapper interface

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-env#428]
### What problem does your feature solve?

Merged #338 without tests.

### What would you like to see?

We need to figure out how to efficiently test this kind of thing. There's not really any machinery for preparing accounts/trustlines right now.

### What alternatives are there?

N/A

**Comment by sisuresh** [comment]
Tests were added in https://github.com/stellar/rs-soroban-env/pull/525, but I'll leave this issue open as a reminder that we still need to audit the code and make sure the tests thoroughly cover all trustline and non-trustline scenarios.

**Comment by dmkozh** [comment]
@sisuresh , assigned this to you as you've reopened this. I suspect this can be closed now though.

**Comment by sisuresh** [comment]
Yeah this can be closed.
