### ISSUE TITLE
bytes_{new,copy}_from_slice shouldn't panic

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-env#434]
### What problem does your feature solve?

`bytes_new_from_slice` and related functions can panic, which could crash the node.

### What would you like to see?

These functions shouldn't panic, but instead should propagate errors.

### What alternatives are there?

Use `catch_unwind`. Stop using these functions in the built-in token (they are only used in two places, so this is possible).

**Comment by jonjove** [comment]
cc @graydon

**Comment by leighmcculloch** [comment]
@jonjove Could you elaborate in what situations these functions can panic:

**Comment by leighmcculloch** [comment]
I don't think this is critical for this next iteration. Is it critical @jonjove @graydon @MonsieurNicolas?

**Comment by graydon** [comment]
These should just be rewritten to not panic. The panics are all avoidable.
