### ISSUE TITLE
DebugEvents do not have a contract ID which makes debug events ambiguous

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#438]
I've noticed that debug events don't have a contract ID stored on them like how ContractEvents do. This makes inspecting the events pretty confusing because it isn't really clear who generated them.

**Comment by graydon** [comment]
As with #442 I'm going to hold off on deciding how to fix this until we've got more signal on the RawVal representation -- I'm seeing lots of cases where a host-wide small number identifier for contracts would be helpful, but it's not totally clear to me where to put it yet / what its scope or semantics should be.
