### ISSUE TITLE
Small bignum optimization / faster bigint

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#445]
We should consider switching our bigint implementation. https://crates.io/crates/ibig is faster and has small-integer optimization (when numbers are only 1 word it only takes 2 words of storage, doesn't heap-allocate).

We might also consider https://crates.io/crates/crypto-bigint which offers, rather than a single never-overflowing big integer type, a variety of fixed-size much-larger-than-normal integer types (U256, U512, U4096, etc.) with operations defined just on those types. I'm not certain whether this sort of thing would be more or less useful to our users.

**Comment by graydon** [comment]
related to #200 in the sense of "finalizing small / efficient versions of all host objects"

**Comment by jonjove** [comment]
The crypto-bigint suggestion is related to https://github.com/stellar/rs-soroban-env/issues/339.

**Comment by graydon** [comment]
Bigint eliminated entirely, we're using {iu}128 now.
