### ISSUE TITLE
Built-in token contract: add function to create wrapper contracts 

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-env#446]
We can only create the non-wrapper version at the moment.

**Comment by sisuresh** [comment]
Clarification - there’s nothing stopping someone from using the built-in token contract as a wrapper for a classic asset at the moment. Anyone could wrap any classic asset and set them selves as the admin. This is incorrect and should be fixed as part of this issue.

**Comment by leighmcculloch** [comment]
Does anything need adding to the SDK, or plumbing through to the SDK, as part of this for it to be used? Or will this be a function on the contract itself?

@sisuresh If something needs plumbing into the SDK, can you open an issue for the SDK repo too?

**Comment by sisuresh** [comment]
This issue is blocking https://github.com/stellar/soroban-cli/issues/81.
