### ISSUE TITLE
Source Account Auth: Use source account/contract in native token contract

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#472]

**Comment by paulbellamy** [comment]
Would be nice to update the call signature for the token.approve method in the example dapp while you're at it:
https://github.com/stellar/soroban-example-dapp/blob/main/pages/index.tsx#L143

**Comment by smac711** [comment]
added to current Soroban Sprint since @leighmcculloch mentioned it is critical.
