### ISSUE TITLE
Difficulty understanding Object parameter types in the host

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-env#503]
For example, it's not clear if the `account_id` below contains a byte vector or `xdr::AccountId`. We should add comments for every `Object` parameter.
```
pub(crate) fn transfer_trustline_balance(
      &self,
      account_id: Object,
      asset_code: Object,
      issuer: Object,
      amount: i64,
  )
```

**Comment by leighmcculloch** [comment]
We should avoid passing around Objects and RawVals as much as possible anywhere where their type should be known or is expected to be trusted. As much as possible they should only exist at the boundary between the guest and the host.

**Comment by leighmcculloch** [comment]
The `transfer_trustline_balance` function is an interesting candidate. The only code calling that function is the token contract itself, and so it is really questionable to me why it would even be using `Object` as a type. At the moment the function is called the type of account_id should be concretely known and validated, so there's no reason we should passing around generic object handles anywhere other than the boundary between the guest and the host.

**Comment by graydon** [comment]
I think this should get _less_ confusing the more specific types we have in XDR, both with the work happening in https://github.com/stellar/rs-soroban-env/issues/679 and anything following from https://github.com/stellar/rs-soroban-env/issues/599 wrapped up. I'm going to close for now but please reopen if this reoccurs as a problem.
