### ISSUE TITLE
Token contract is easy to misuse because of similar function params

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#520]
Something I'm noticing when looking at invocations of the token contract, is that it is difficult to remember which arguments are for what intent and purpose.

Take this code plucked from one of the examples:

<img width="337" alt="Screen Shot 2022-10-03 at 11 42 47 PM" src="https://user-images.githubusercontent.com/351529/193751661-7bee530f-18b1-4a53-a24a-902b1337e6e4.png">

It's difficult, for me at least, to remember what the third and fourth arguments are, and which direction money is flowing between them.

The token contract is one contract that may benefit from collecting inputs in request objects/values. For example:

<img width="337" alt="Screen Shot 2022-10-03 at 11 42 01 PM" src="https://user-images.githubusercontent.com/351529/193751544-6f9c82e1-6f2d-4f13-91a0-96867d16c95e.png">

One of the advantages of request objects/values in languages like Rust that do not support named arguments on functions is the increase verbosity at call sites.

Unfortunately there's a significant downside of doing this with Soroban contracts. The flat argument list is cheaper both on the Soroban side, and in the Stellar transaction.

Maybe there are other things we could do to achieve the same affect without the same cost.

**Comment by sisuresh** [comment]
This is very old, and we've already finalized the token interface, which is simpler than the one we had when this issue was created.
