### ISSUE TITLE
Improve token contract error reporting

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-env#526]
The token contract returns the same generic error code for all failure cases ([example](https://github.com/stellar/rs-soroban-env/blob/354b1fc9ef215eb37d8af5e6419071dfaaeddd2d/soroban-env-host/src/native_contract/token/contract.rs#L117)). This makes it difficult to debug errors.

**Comment by leighmcculloch** [comment]
If the contract returns Status's with contract errors, or implements the `contracterror` macro from the SDK, then it could surface meaningful errors to contracts who can optionally catch them.

**Comment by sisuresh** [comment]
Resolved by https://github.com/stellar/rs-soroban-env/pull/532.
