### ISSUE TITLE
Add Asset as a first-class ScObject

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#537]
We need to add Asset as a first-class ScObject, with host functions for constructing and deconstructing it.

Blocking https://github.com/stellar/rs-soroban-env/issues/538, https://github.com/stellar/rs-soroban-sdk/issues/730

**Comment by graydon** [comment]
Is this still meaningful, @leighmcculloch ?

**Comment by leighmcculloch** [comment]
Unclear. We just removed the only SDK function that used asset. We might have to bring it back for testing. If that happens we should revisit this. Otherwise I think we could pass on it for now.
