### ISSUE TITLE
Add host functions that calculate contract IDs from inputs

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#538]
We need a set of host functions that will return contract ID (as Bytes) given a set of inputs.

We have the following functions that can create contracts:
https://github.com/stellar/rs-soroban-env/blob/4f2f3a2da58dd869b559f41311815b20d1552ce5/soroban-env-common/src/env.rs#L307-L321

In total we need to add `12` new host functions:

- `7` new host functions that are counter-parts to the host functions above, that will return the contract ID that will be used if the deployment was to occur by calling the respective function.
   - `get_contract_id_contract_from_ed25519(salt: Object, key: Object) -> Object`
   - `get_contract_id_contract_from_contract(salt: Object) -> Object`
   - `get_contract_id_contract_from_source_account(salt: Object) -> Object`
   - `get_contract_id_token_from_ed25519(salt: Object, key: Object) -> Object`
   - `get_contract_id_token_from_contract(salt: Object) -> Object`
   - `get_contract_id_token_from_source_account(salt: Object) -> Object`
   - `get_contract_id_token_from_asset(asset: Object) -> Object`

- `2` new host functions for getting the contract ID for a deployment from contract that isn't the currently executing contract.
   - `get_contract_id_contract_from_other_contract(contract_id: RawVal, salt: Object) -> Object`
   - `get_contract_id_token_from_other_contract(contract_id: RawVal, salt: Object) -> Object`

We can omit any of these host functions that would always return the same value given the same inputs. For example, I expect we can omit all the token functions except the one that accepts an asset, 

Dependent on https://github.com/stellar/rs-soroban-env/issues/537
Blocking https://github.com/stellar/rs-soroban-sdk/issues/730

**Comment by jayz22** [comment]
@leighmcculloch Is this issue still relevant? Most of the mentioned host functions have been removed and the mentioned issue has been closed.

**Comment by leighmcculloch** [comment]
Yeah it should be possible for us to write an SDK function that helps a developer predetermine a contract ID that would be the contract ID of a contract when deployed.

**Comment by leighmcculloch** [comment]
The infrastructure around deployments has changed a lot, so the examples in the original issue are out of date.

**Comment by jayz22** [comment]
We currently have two host functions for creating a contract:

```
                    "name": "create_contract",
                    "args": [
                        {
                            "name": "deployer",
                            "type": "AddressObject"
                        },
                        {
                            "name": "wasm_hash",
                            "type": "BytesObject"
                        },
                        {
                            "name": "salt",
                            "type": "BytesObject"
                        }
                    ],
```
```
                    "name": "create_asset_contract",
                    "args": [
                        {
                            "name": "serialized_asset",
                            "type": "BytesObject"
                        }                        
                    ],
```

So we just need two additional host functions given the same arguments and returns the contract_id without creating? 

> 2 new host functions for getting the contract ID for a deployment from contract that isn't the currently executing contract.

@leighmcculloch Can you confirm if this statement is outdated?

**Comment by jayz22** [comment]
@leighmcculloch  I've created the [PR](https://github.com/stellar/rs-soroban-env/pull/853) above which adds two new host functions corresponding to contract and asset contract. I think this should cover all the scenarios originally requested to unblock the sdk?

**Comment by leighmcculloch** [comment]
@jayz22 It looks great 👏🏻. That was fast!
