### ISSUE TITLE
Soroban-Focused Native Token Interface

### ISSUE THREAD

**Issue by mootz12** [stellar/rs-soroban-env#549]
### What problem does your feature solve?
The current native token interface sits in-between a traditional ERC-20 interface and a custom Soroban geared token model. I am proposing a token model that attempts to better separate these lines.

There are also concerns over the amount of `calldata` forcing `Signatures` to be passed as arguments will create. I'm not sure how rollups will be implemented in Soroban yet so this could be a non-issue, but this is a problem Ethereum has been dealing with for awhile ([EIP-4488 provides some context](https://eips.ethereum.org/EIPS/eip-4488)). The effects are also present in the [Aave v3 L2 contracts](https://docs.aave.com/developers/getting-started/l2-optimization).

This issue is primarily to open a discussion around this.

### What would you like to see?
A new interface for the token contract as follows:

```rust
pub trait TokenTrait {
    fn init_asset(e: &Host, asset_bytes: Bytes) -> Result<(), Error>; // unchanged

    fn init(e: &Host, admin: Identifier, metadata: TokenMetadata) -> Result<(), Error>; // unchanged

    fn nonce(e: &Host, id: Identifier) -> Result<BigInt, Error>; // unchanged

    /// Calldata-lite, simple options - all use invoker based auth, almost a full replica of base Ethereum ERC-20
    /// Easier (and only 1 signature required) for users to directly transfer tokens

    fn allowance(e: &Host, from: Identifier, spender: Identifier) -> Result<BigInt, Error>;

    fn approve(
        e: &Host,
        spender: Identifier,
        amount: BigInt,
    ) -> Result<(), Error>;

    fn balance(e: &Host, id: Identifier) -> Result<BigInt, Error>;

    fn xfer(
        e: &Host,
        to: Identifier,
        amount: BigInt,
    ) -> Result<(), Error>;

    fn xfer_from(
        e: &Host,
        from: Identifier,
        to: Identifier,
        amount: BigInt,
    ) -> Result<(), Error>;

    // verifies invoker is admin
    fn mint(
        e: &Host,
        to: Identifier,
        amount: BigInt,
    ) -> Result<(), Error>;
    
    // verifies invoker is admin
    fn burn(
        e: &Host,
        from: Identifier,
        amount: BigInt,
    ) -> Result<(), Error>;

    /// Flexible option - the one pre-signed function to rule them all
    /// - The ledger timestamp is validated to be less than expiration
    /// - Signature validates that `from` signed a message containing the correct nonce and 
    ///   remaining parameters (from -> expiration).
    /// - Any action where `from` is the token contract must be signed by the admin to be valid
    fn xfer_sig(
        e: &Host,
        sig: Signature,
        from: Identifier,
        to: Identifier,
        amount: BigInt,
        expiration: u64
    );

    // all general management is left unchanged
    fn is_frozen(e: &Host, id: Identifier) -> Result<bool, Error>; // unchanged

    fn freeze(e: &Host, admin: Signature, nonce: BigInt, id: Identifier) -> Result<(), Error>; // unchanged

    fn unfreeze(e: &Host, admin: Signature, nonce: BigInt, id: Identifier) -> Result<(), Error>; // unchanged

    fn set_admin(
        e: &Host,
        admin: Signature,
        nonce: BigInt,
        new_admin: Identifier,
    ) -> Result<(), Error>; // unchanged

    fn decimals(e: &Host) -> Result<u32, Error>; // unchanged

    fn name(e: &Host) -> Result<Bytes, Error>; // unchanged

    fn symbol(e: &Host) -> Result<Bytes, Error>; // unchanged

    fn import(e: &Host, id: Signature, nonce: BigInt, amount: i64) -> Result<(), Error>; // unchanged
    
    fn export(e: &Host, id: Signature, nonce: BigInt, amount: i64) -> Result<(), Error>; // unchanged
}
```
This interface allows for EOA's and Stellar accounts to have a much simpler time interacting with the token contract directly, as they only need to sign the invoking operation. Further, it allows for simpler contracts to be created that don't need to rely on `soroban-auth` for basic use cases. This comes at a current cost of not allowing any pre-signed invocations to be made.

The new function `xfer_sig` provides all the mechanisms necessary to safely transfer tokens from one party to another through an expiring signature. L1 contracts can utilize this to complete `xfer_from` in one transaction instead of two without the user managing approvals. Further, it introduces an expiration that was missing in the current `permit` implementation (see https://github.com/stellar/sorobanathon/discussions/30). The downside is that `xfer_sig` can't approve, so contracts that only have this implemented will need to fetch two signatures each time they want to execute a function.

### What alternatives are there?
The function `xfer_sig` can technically implement all required token transfer methods. However, I think providing options to use simpler authentication techniques is worth including the extra ERC-20 functions for.

Instead of `xfer_sig`, a specific `permit` function can be added that follows the specifications in [EIP-2612](https://eips.ethereum.org/EIPS/eip-2612) to allow for single transaction usage, thus making the native token interface an exact replica of the ERC-20.

**Comment by dmkozh** [comment]
Thanks for the great feedback and proposal!

I think it points at some general issues we have now with the auth approach (please correct me if you think I'm wrong somewhere and feel free to add your points):

- Mixing invoker and generic signatures is inconvenient. Invoker doesn't need to pass signature and we also have a 0 nonce that we still have to pass, even though it's a no-op (that hasn't been mentioned here, but I believe that's a problem too).
- Signature-less fns are more convenient to use (and from my point of view also more convenient to test), but currently the token doesn't provide that as an option
- There is no good way currently to prevent front-running or re-using the pre-signed operations. `expiration` is one of the things to prevent that to some degree.
- Token interface is of course useful to make more ergonomic, but for any developer of a reusable generic contract (e.g. AMM) the same issues would need to be addressed. I think it would be nice if new contracts could be composed with each other and with built-in token without much tension.

BTW I also think that import/export are good candidates for invoker auth (probably even better than anything else), as currently these are meant to be called by classic accounts only.

**Comment by mootz12** [comment]
The general issues you called out do a good job summarizing my pain points as well.

Some additional notes:
> There is no good way currently to prevent front-running or re-using the pre-signed operations. expiration is one of the things to prevent that to some degree.

I realized the original proposal is missing this. But, the `xfer_sig` method can force the `from` to also be the `invoker`. Thus, the signature can't be front-run by anyone listening to the incoming transactions, and contracts that utilize this can safely proceed under the assumption that only they can process the pre-signed transaction. 

> BTW I also think that import/export are good candidates for invoker auth (probably even better than anything else), as currently these are meant to be called by classic accounts only.

Good catch - I agree.

**Comment by sisuresh** [comment]
I believe auth-next addresses the main concern here by no longer passing signatures into functions. The token interface will still take the authorizing `Address` as a parameter, but I think this is fine for now. If we run into issues with the amount of `calldata`, I think we'll have to figure out a more general solution. @mootz12 and @dmkozh what do you think?

**Comment by dmkozh** [comment]
I've opened https://github.com/stellar/rs-soroban-env/issues/653 to track Auth Next-specific token interface changes.

We can (and I think should) get rid of the input addresses for the admin ops. Not so sure for everything else, given that signatures no longer need to be passed via the interface. Maybe we could consider developing on ideas in https://github.com/stellar/rs-soroban-env/issues/660 and make 'single authorized address' functions first class citizens given that they would probably cover 50+% of the contract use cases (that's my guesstimate, I could be completely wrong here, but seemingly so far people could do a lot even with just the `invoker`). Not sure how the interface should look like though.

**Comment by sisuresh** [comment]
Sounds good. I think we can close this issue then. And re: interface- it would be ideal if we could avoid the fragmentation of token contracts between ones that allow a `from` address in `xfer` and ones that don't. I agree that this 'single authorized address' would cover a good number of cases and is something we should explore, but I feel like the most commonly called contracts (like liquidity pool deposit or swap) would benefit from non-invoker token support.

**Comment by mootz12** [comment]
Looks like `auth-next` and the respective interface changes in #653 address the concerns I had when creating this issue.
