### ISSUE TITLE
ensure float is turned off

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#563]
It looks like we might not be properly disabling floating point ops:

https://github.com/stellar/rs-soroban-sdk/pull/753

We need to make sure they're _really_ turned off.

**Comment by jayz22** [comment]
I can take a look at this issue.

**Comment by graydon** [comment]
Depends on upgrading wasmi, which depends on hooking up to wasmi's new metering system.

**Comment by jayz22** [comment]
Resolved in https://github.com/stellar/rs-soroban-env/pull/815
