### ISSUE TITLE
object handle integrity

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#569]
object handles entering the system from SCObject -> HostObj -> guest Object handle conversion have their type tags set correctly, but a cross-contract call can forge an object handle with an invalid tag. This can't corrupt the host -- the host ignores those tags, they're supposed to just be informative to save round trips inquiring about types -- but it can lead to some potential confusion or latent corruption in guest code that acts on the basis of forged tags.

@leighmcculloch suggested a nice fix to this which is to enforce integrity while we're plumbing RawVals from one contract to another (either as calls or returns) such that a forged handle causes the forger to trap. This is a good idea and we should do it.

**Comment by graydon** [comment]
From conversation on discord (https://discord.com/channels/897514728459468821/1104886726700322956) it seems like it might also be useful to expose a general "rawval validation" host function. I think this would be easy to include with this work.

**Comment by anupsdf** [comment]
Setting target milestone to `Testnet Phase 1` after discussing with @graydon

**Comment by graydon** [comment]
I'm actually going to approach this a little differently: rather than check "when calling" I'm going to check "when constructing vectors" (or other containers). For two reasons: first it's necessary to ensure that object integrity holds in all objects _reachable_ through a container reference (not just the reference itself); and second it's sufficient to check container construction because call argument lists _are_ vectors.

**Comment by leighmcculloch** [comment]
> rather than check "when calling" I'm going to check "when constructing vectors" (or other containers)

Does this mean there's no integrity checks outside containers?
