### ISSUE TITLE
Document the token interface events emitted in the docs

### ISSUE THREAD

**Issue by paulbellamy** [stellar/rs-soroban-env#577]
### What problem does your feature solve?

Consumers may wish to depend on the events emitted by a token/asset contract.

### What would you like to see?

Add the events into [the docs](https://soroban.stellar.org/docs/common-interfaces/token), so people can depend on it.

### What alternatives are there?

Exclude events from the interface?

**Comment by sisuresh** [comment]
@paulbellamy Closing since the events were added as comments above each function in the interface [docs](https://soroban.stellar.org/docs/common-interfaces/token). Please reopen if you think this isn't sufficient or if you have suggestions.
