### ISSUE TITLE
Object subtypes

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#583]
Currently the `Object` type carries a 28-bit type code and a 32-bit handle. The type-code space is needlessly large and we have uses for subtypes. We should split the type-code space to allow subtypes:

- Text as a subtype of Bytes
- WASM as a subtype of Bytes
- Cryptographic keys and hashes as subtypes of Bytes
- Timestamp as a subtype of integers
- Bitset as a subtype of integers and/or bytes (freeing up an SCVal / RawVal tag)
- Fixed-point numbers with specific scale factors as subtypes of integers (we can chew up 18 or so subtype-tags with this, or whatever the maximum reasonable scale factor is)

Subtypes should be optional whereas types are mandatory (they specify a representation). Subtypes indicate special formatting (eg. displaying text literally rather than as hex escapes, displaying timestamps as ISO8601 rather than numbers, displaying fixed-point numbers with the correct precision) and/or special handling in some-but-not-all host functions (eg. iterating over text by UTF-8 codepoint or performing date arithmetic on timestamps).

We've discussed this before and the conversations went around in circles but we have real pressing issues with at least two of these (Text and Fixed-point) and I'm quite certain the others will benefit from protocol-level support for subtypes further on. I don't think we should delay further.

**Comment by jayz22** [comment]
I'm also wondering if it would be possible or if its' a good idea to encode some information about the Object's size/nestedness. 
In light of the [limited ScVal](https://github.com/stellar/stellar-protocol/issues/1298) discussion, and the discussions around [flattening ScObject](https://github.com/stellar/stellar-xdr/pull/64#issuecomment-1398977913), maybe a good way provide more insight of the object's structure to the user is to encode the number of ScObjects nested within it. This could help with metering too, by knowing the number of nested objects we can charge the budget accordingly.

**Comment by graydon** [comment]
We're only going to do a few of these -- `TimePoint` and `Duration` as subtypes of `U64`, and `String` as a variant of `Bytes`. General mechanism will not be deployed, specifics to occur as part of [flattening ScObject](https://github.com/stellar/stellar-xdr/pull/64) as part of #679. Closing this one given that fact.
