### ISSUE TITLE
Bulk vec initialization for tuples

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#596]
Most of our host objects and host functions are "point-based", which makes some code needlessly expensive. Mainly when converting UDTs to and from maps and vecs, we make multiple temporaries and make multiple host function calls -- one per field -- when we could get away with some "bulk" operations fairly easily that pass more than one value in each direction. For example we could initialize a 4-element map with `push, push, push, push, new_map_4` instead of `push, new_map, push, map_push, push, map_push, push, map_push` as we do today. These costs add up, and I think UDT code is one of our main cost amplifiers right now.

As with the multi-word experiments, we might find there's a saddlepoint between functions that take up-to-N arguments and a single function that takes a linear-memory slice pointing to a local array of rawvals (at least for inputs). For outputs, probably anything less than the saddlepoint is going to be no cheaper to bulk-extract than pointwise-extract, because of the overhead of setting up the array and bouncing arguments through it. My guess is that the saddlepoint is around 6 or 8 arguments, but it could be a ways off in either direction.

**Comment by leighmcculloch** [comment]
+1 most of the types I'm seeing are also small. Enums are often 2 elements, and if we could create the vec and pass 2 elems in a single call, that'd be great 👏🏻. Many structs are also small.

**Comment by graydon** [comment]
done in https://github.com/stellar/rs-soroban-env/pull/682

**Comment by graydon** [comment]
Actually there's still a bit to do here on tuples in common. Reopening for now.

**Comment by graydon** [comment]
As of #730 this is done.
