### ISSUE TITLE
Add Stellar-classic types back to SCObject as needed

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#599]
The builtin contract has code in it like this:

https://github.com/stellar/rs-soroban-env/blob/5cd4ffa59e055ae7e12954fea9e2440fd2e8c5ab/soroban-env-host/src/native_contract/token/public_types.rs#L112-L114

Which clearly exists just to re-encode a Stellar-classic asset as a Soroban UDT -- a mix of vectors and maps -- but with strictly worse performance, code-maintenance costs and risk of incompatibility.

I think the motivation that got us here was to keep Soroban "agnostic" about Stellar assets and other Stellar-classic protocol entities, keeping them out of (say) the XDR definition of SCObject and the Rust definition of HostObject. I voiced my opinion at the time that this was overkill, and that anyone trying to use Soroban outside Stellar could fairly easily delete or mark-as-unsupported a couple entries they didn't care for in the SCObject type list, whereas the benefit to us from _supporting_ them would be fairly high. I was overruled at the time, but I believe this point still stands and experience has shown us that the code spent projecting Stellar-classic concepts in and out of Soroban's repertoire would be better spent on other things: we can just _embed_ the types directly. They're already well defined in the XDR and its Rust translation.

We're [already doing this with AccountId](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/host_object.rs#L24) and it works fine.

Obviously I don't want more datatypes in Soroban than necessary, but any time we're doing this -- either in the interfaces to contracts or even in the implementation of (eg.) the builtin Stellar-asset token contract -- we should just do the same thing as with AccountId and embed the XDR of the type in question directly into the SCObject / HostObject repertoire: Assets, possibly Thresholds, Weights, Signers or other Signature metadata, possibly Liabilities or Flags, possibly as much as an entire Account or TrustLine ledger entry. Whatever we actually need for interop.

If users want to inspect a specific field of it we can provide a projection or accessor, but most likely they'll just have a handful of operations they want to perform, implemented in host code, and manually re-encoding the type as a UDT is a waste.

**Comment by leighmcculloch** [comment]
There is something that's different about account vs asset, in that most networks have some notion of an accont, and it is rather broad, and we've made `AccountId` opaque within a contract. i.e. You can have a reference to an account ID, but it is mostly designed for being used as a key. So Soroban could be used on another chain and that "account ID" could just be a key without any special meeting.

While I agree account ID is a step in this direction, it is maybe a few toes in the door, vs assets which is maybe a full limb in the door.

I'm not strongly opposed to adding asset.

But I think the larger issue here is that UDTs are expensive. Can we try to address that problem first and see if it is still worth addressing the Asset issue independently?

**Comment by leighmcculloch** [comment]
Will https://github.com/stellar/rs-soroban-env/issues/596 make UDTs efficient enough do you think?

**Comment by graydon** [comment]
I think it will cheapen them, as will moving away from `im` (in #585) but there's no way to make a k-v representation with explicit symbolic keys, accessed by binary search, perform as well as a struct with no keys that you access fields out of by offset. It's always going to be slower and bigger, just by definition.

Anyway, to me the performance issue is of less concern here than the duplication of concepts and potential divergence. Why have two separate-and-not-quite-identical representations of a thing in a contract whose whole point is interop?

**Comment by graydon** [comment]
@dmkozh and @sisuresh do you have thoughts on this? I know the SAC discussion has seen a lot of back-and-forth about which concepts from the classic world to wire-in to the value repertoire in the soroban world.

**Comment by dmkozh** [comment]
`AccountId` is now moved into the `ScAddress`/`Address` type, so it's even more opaque now from the contract perspective.

The assets are a in a bit weird place: the only use case for them is to initialize the asset contract. I'm not quite sure this is worth maintaining more object types. OTOH if they're completely internal (like 'contract code'/auth next nonce entries), then probably there isn't much difference.

**Comment by sisuresh** [comment]
The `Metadata` contracttype (which maps to the xdr `Asset`) is only used internally in the SAC like Dima said, but we already have object types for internal concepts like the nonce so I think it would make sense to do the same in the SAC. This would also give us the flexibility to use the `Asset` type in other ways if we need to in the future.

**Comment by graydon** [comment]
I don't think there's anything specific to do on this bug; specific further extensions can get their own bugs but at this point we've long since locked in the object repertoire (and Asset did not make the cut). Closing.
