### ISSUE TITLE
Error messages are incorrect

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-env#622]
### What did you do?
```rust
Err(err!(
    e,
    ContractError::BalanceError,
    "balance is not sufficient to spend: {} < {}",
    balance,
    amount
))
```

### What did you expect to see?
```
Debug events (newest first):
   0: "balance is not sufficient to spend: Object(I128(#403)) < Object(I128(#404))"
```

### What did you see instead?
```
Debug events (newest first):
   0: "balance is not sufficient to spend: Status(ContractError(11)) < Object(I128(#403))"
```

The `err` macro, which calls `host.err_status_msg_with_args` is treating the status as an arg, but we use it with the expectation that it's already taken care of in the message, resulting in the loss of one of the arguments and an incorrect error message.

**Comment by jayz22** [comment]
Nice explaination @sisuresh. I think this issues is overlapped with of https://github.com/stellar/rs-soroban-env/issues/379 which unfortunately was not fixed at the time. We should address them together.

**Comment by 2opremio** [comment]
There's another problematic error: `"balance is not sufficient to spend: Status(ContractError(11)) < Object(I128(#34))"`
