### ISSUE TITLE
Finalize contract and instance metadata

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/rs-soroban-env#630]
We need to decide on how to attach metadata to contracts and instances.

Current prototype attaches it to the WASM blob itself using a WASM section.

(ongoing discussion - issue is here for tracking)

**Comment by sisuresh** [comment]
Closed by https://github.com/stellar/rs-soroban-sdk/pull/914 and https://github.com/stellar/rs-soroban-sdk/pull/907
