### ISSUE TITLE
Consider making decimals in the Stellar Asset Contract configurable

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-env#643]
Making the Stellar Asset Contract return a configurable decimal value instead of a constant value of 7 is a suggestion @leighmcculloch made [here](https://github.com/stellar/rs-soroban-env/pull/607/files#r1044890673). This issue contains two questions we need to answer - 

1. Is this a good idea?
2. How would we implement this?

**Comment by sisuresh** [comment]
@leighmcculloch do you think this is important?

**Comment by leighmcculloch** [comment]
Unclear, we'd need to poll the ecosystem I think. cc @namankumar Closing until it's identified as important.
