### ISSUE TITLE
Split out contract event validation from conversion. Have event buffer contain `Val` references only. 

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#648]
First discussed [here](https://github.com/stellar/rs-soroban-env/pull/640#issuecomment-1412730583). 

The contract events are currently eagerly converted from `Object` + `RawVal` ("topics"+"data") to XDR, and keep in the event buffer. This makes event buffer large and expensive in terms of metering (e.g. cloning it in the case of rolling back a failed contract). 

The original reason for doing it this way was to make validating the "topics & data" structures easier (not having to walk the structures twice). But the validation and conversion to XDR steps should be separated.

**Comment by jayz22** [comment]
Self-assigned the issue due to its impact on metering. Also I was the one who created it.

**Comment by dmkozh** [comment]
While discussing the further events work (https://github.com/stellar/rs-soroban-env/pull/713#discussion_r1134695543) I've noticed that the current format still seems suboptimal. If we want events to be cheap to copy, we could just use `Rc` with whatever object that makes the most sense (XDR?). The reason to do that is that with the current approach the internal debug events have to do an unnecessary host object roundtrip (i.e. host object is allocated and accessed without ever moving out of host). I suppose a reason not to go this route would be if the contract events can be recorded, but never converted to XDR, but I'm not sure if that ever should be the case. Any thoughts? @jayz22 @graydon

**Comment by jayz22** [comment]
One potential benefit I see if memory efficiency. Converting a `RawVal` into `ScVal` clones the underlying contents and keeps them in the heap. Doing that eagerly means we are paying for that heap memory conversion upfront and keeps that in our memory footprint throughout the host's lifetime (even though Rc ensures that only one instance of that heap footprint exist). Since contract events don't currently have size limit in key (https://github.com/stellar/rs-soroban-env/issues/629) and can put any ScVal in their data, this can increase the peak memory footprint significantly. 
Doing the conversion lazily ensures the memory cost is delayed, and doesn't impact the peak memory, since the conversion only happens when the host is winding down (either via `try_finish` or when an error occurs).

**Comment by dmkozh** [comment]
That's fair. Also I think that given that a big (and not explicitly bounded) chunk of events can come from the custom user events, it makes more sense to optimize for them in the first place, so I suppose the current approach should work fine (though a top-level `Rc` in theory could still be more efficient in case if we store any long-living event copies, no matter the internal strcture).
