### ISSUE TITLE
Consider removing the get_current_call_stack host function

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-env#661]
`get_current_call_stack` was initially added to support adding context when authorizing nested contract calls (but we never got around to using it). Now that we have auth-next (@dmkozh), this function is no longer needed. Unless we think users will want this host function to implement some form of custom auth, it should be removed.

**Comment by dmkozh** [comment]
I believe the same reasoning applies to the network identifier (the main use of it would be in the signature payloads as well). That said, I'm not entirely sure if both functions are completely useless outside of the signature context.

**Comment by jayz22** [comment]
@sisuresh @dmkozh What are the actions needed to decided if the `get_current_call_stack` and the `get_ledger_network_id` functions can be removed? Shall we try removing them (if you can't think of an essential use case) and see if they break things, or mark them for deprecation so new developers don't depend on them?

**Comment by dmkozh** [comment]
I would tentatively vote to leave them be, unless we think the maintenance cost is too high. Call stack can be useful to ensure some indirect contract dependencies (e.g. imagine the set of DEX-related contracts that all want to be routed through the DEX owner's contracts; this can be easily achieve if call stack is available). Network id is probably useful too for some more creative use of signatures beyond what auth next provides (maybe for something like bridges, though I'm not familiar with implementation of these).

**Comment by sisuresh** [comment]
I agree that this info could be helpful for some creative contracts. Lets leave them then and I'll close this issue. We can revisit if need be.
