### ISSUE TITLE
Auth Next: Revamp auth verification interface

### ISSUE THREAD

**Issue by dmkozh** [stellar/rs-soroban-env#663]
Suggested by @leighmcculloch:

Could we add a new function that gets a Vec<> of require authorizations that have been called? The way this would be written in a test would then be something like this:

```rust
client.transfer(&address, &1000_i128);
assert_eq!(
    env.auth().all(),
    std::vec![
        (&address, &contract_id, "transfer", (500_i128,).into_val(&env)),
    ],
);
```

Writing the test this way has several advantages:

- If someone doesn't know what is going on they can print out all the authorizations.
- The assert_eq will print out the full list of authorizations if they don't match what is expected.

To add to that, we can have two functions: one returning the vector of top authorizations and another one returning the whole tree.

**Comment by dmkozh** [comment]
One tricky thing here is ordering, so we either need to find some good `unordered_eq` test util or implement matching as a part of SDK (which is less flexible, but more practically usable).

**Comment by leighmcculloch** [comment]
I think Rust ecosystem will cover us with this one, with crates like [assert_unordered](https://docs.rs/assert_unordered/0.3.5/assert_unordered/).

It's also not difficult to do things like check for a single auth as opposed to all auths:
```rust
env.auth().all().iter().any(|a| a == (&address, &contract_id, "transfer", (500_i128,).into_val(&env)))
```

But I reckon in the average case ordered results will probably be fine. In many contracts ordering will be deterministic.

**Comment by dmkozh** [comment]
I just don't really want to be super precise about the recording order here, especially for the tree case. OTOH I think it should match what you would expect most of the time, so that's probably ok.

**Comment by sisuresh** [comment]
@dmkozh is this done or should we keep it open and update it to indicate that we still need to add support for the full tree?

**Comment by dmkozh** [comment]
Let's close this and I'll open another issue the full tree for the sake of clarity.
