### ISSUE TITLE
Auth Next: Audit the metering

### ISSUE THREAD

**Issue by dmkozh** [stellar/rs-soroban-env#668]
The metering code is a bit hand-wavy in Auth Next; we should audit it and make sure it's properly metered. Additional care needs to be applied to make sure that metering in recording mode is as close enough to enforcing as possible.

**Comment by graydon** [comment]
@dmkozh None of the containers (vectors, hashtables) in auth-next are metered at all, right? It seems to me like there's a fairly large set of changes still to make here, not just auditing.

**Comment by dmkozh** [comment]
The containers are internal and I don't think they should be metered directly (similar to e.g. the host stack frames that are just stored in the regular `Vec`s) - that seems unnecessarily slow and complex. But we might want to introduce some top-level budget charges to account for some auth operations in bulk. That's why the issue is about 'audit' in the first place - we need to figure out what are the metering gaps and how to account for them properly (if at all).

**Comment by graydon** [comment]
In general we're only able to capture costs that are constant or linear-in-some-input-size, and everything else has to be broken down to those. So unless top-level auth calls are constant or linear cost, they'll likely need _some_ decomposition. And the elements that make up the decomposition (even if it's just top-level) need to be registered as `CostType`s in the XDR and have calibration code written for them and so on. It's not just a finishing-touches sort of thing, it can be fairly involved.

**Comment by dmkozh** [comment]
Sure, I don't think this issue mentions anything with respect to the scope of the work. From a brief overview I don't think the things are too bad, but I'd appreciate another pair of eyes looking at this:

- Host object allocations are metered
- Clones are metered (at least for the most part, maybe there is an oversight somewhere)
- Account authentication logic (likely the most expensive part) is metered
- Storage reads (for nonce verification)

What is not metered:
- Interactions with a couple small vectors (iteration, allocation)
- A bunch of if statements

It seems to me that we maybe need to add one low-level operation to account for the deepest iteration level (as to capture the overall complexity) to capture the complexity, though even for that I'm not 100% certain. But again, I'd appreciate a second opinion on this.

**Comment by jayz22** [comment]
I did a very high level look of the auth. These are the issues I think needs addressed:
- `tracker_by_address_handle` is currently using `std::HashMap`. It is not metered but more importantly, we should avoid using HashMap for canonicalization reasons -- we want to avoid depending on external hashing which may change in the future. `MeteredOrdMap` should be good a replacement here. 
- The internal data structures are not metered. 
    - `call_stack: Vec<ContractInvocation>`. This might be okay since it is called during the host stack operations, which can be covered under `GuardFrame`, and `ContractInvocation` is fixed-sized.
    - `AuthorizationTracker`, `AuthorizationManager`, `AuthorizedInvocation`: this is probably the most problematic issue. `AuthorizedInvocation` contains an `args: ScVec`, and itself is a nested structure containing `sub_invocations: Vec<AuthorizedInvocation>`.  `AuthorizationManager` contains `Vec<AuthorizationTracker>` (which contains `AuthorizedInvocation`).  These structures can potentially be quite large and their operations (e.g. insertion/deletion, allocating, cloning) has to be metered. Some of these may need to be changed to store `Rc` or `Weak` instead of the full structure.

Host objects, storage logics, host calls are shared with the host and should be covered. Some cloning/allocation might be missing coverage. But those are relatively minor. 

I will come up with a suggested list of improvements.

**Comment by dmkozh** [comment]
> we should avoid using HashMap for canonicalization reasons -- we want to avoid depending on external hashing which may change in the future.

I'm not sure why this matters; hash map iteration is usually not stable and the code doesn't rely on that; it only uses it for the map interface (k->v lookups).

> MeteredOrdMap should be good a replacement here.

I'm not sure if that's a good replacement as it produces a lot of redundant objects. More importantly, the map doesn't store the host objects, which is currently what the metered containers use for the values. Can we instead just meter the tracker creations? I'm not sure if it's a good idea to expose some implementation details via metering, while also making them objectively slower.

> call_stack: Vec<ContractInvocation>. This might be okay since it is called during the host stack operations, which can be covered under GuardFrame, and ContractInvocation is fixed-sized.

FWIW this is in line with how the host call stack data structure is not metered.

> These structures can potentially be quite large and their operations (e.g. insertion/deletion, allocating, cloning) has to be metered

I've tried to use metered clone where appropriate (probably not everywhere), but also some things are just moves. I also don't think anything is really shared to warrant rc usage, though I might be wrong.

**Comment by jayz22** [comment]
> I'm not sure if it's a good idea to expose some implementation details via metering, while also making them objectively slower.

I'm not sure what you mean here. We are just replacing one (foreign) data structure with another one (that we own), there is no breaking of encapsulation or anything. 
Also, I'm not sure if the slower argument is true. We are dealing with small containers (with a few dozen elements at most?) and the metered vector/map implementation is designed for that. 
What is the read/write pattern in enforcing mode? Is the tracker just for lookups and reads? If so there is no redundant objects created.  I would doubt the hash based look up (HashMap) is any faster than the binary-search based (MeteredOrdMap). If there is concrete evident of performance issue we can address that but I would err on the safe side.

> More importantly, the map doesn't store the host objects, which is currently what the metered containers use for the values. 

That's not true. `MeteredOrdMap` can store any value that implements MeteredClone. We use it for host storage also (which stores `Rc<LedgerEntry>`).  

> These structures can potentially be quite large and their operations (e.g. insertion/deletion, allocating, cloning) has to be metered

This [comment](https://github.com/stellar/rs-soroban-env/pull/789#discussion_r1181857412) is what I'm referring to.
