### ISSUE TITLE
Add support for Keccak-256 and SHA3 hashing

### ISSUE THREAD

**Issue by tomerweller** [stellar/rs-soroban-env#676]
This is widely supported in the cryptocurrency ecosystem and a pre-requisite for some bridges

**Comment by re1ro** [comment]
I am not sure if it's going to work but there is a way to compile `ethabi` without the `std` and other libs by disabling [default features](https://github.com/rust-ethereum/ethabi/blob/master/ethabi/Cargo.toml#L32).
```
# Cargo
[dependencies]
ethabi = { git = "https://github.com/rust-ethereum/ethabi", branch = "master", default-features = false }
```

**Comment by tomerweller** [comment]
Adding SHA3-256 to this issue as it's the same algorithm as Keccak-256 (minus [a padding difference](https://crypto.stackexchange.com/questions/15727/what-are-the-key-differences-between-the-draft-sha-3-standard-and-the-keccak-sub)) and both are usually provided by the same libraries ([rust example](https://docs.rs/sha3/0.10.7/sha3/)).

**Comment by graydon** [comment]
WIP change here: https://github.com/stellar/rs-soroban-env/pull/839

**Comment by jayz22** [comment]
Resolved by https://github.com/stellar/rs-soroban-env/pull/839
