### ISSUE TITLE
Detect/avoid double-faulting in the host runtime

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#687]
We've recently encountered a case where host function faults, tries to generate a `DebugError` with the error status. While in the middle of creating a `DebugEvent`, it runs out of budget and faults for the second time with an "out of budget" status. The original status was overridden. 

This is a potential footgun. We need to avoid such double/multiple-faulting cases, or at the very least, be able to detect it. One potential solution @graydon suggested was to add a static counter to track the number of times the host have faulted, and asserting that number cannot exceed 1. 

_How to reproduce it:_
Revert changes mentioned in [this comment](https://github.com/stellar/rs-soroban-env/pull/662/files#r1096318055), and run the `metered_xdr_out_of_budget` test under `budget_metering`.

**Comment by graydon** [comment]
Done in https://github.com/stellar/rs-soroban-env/pull/806
