### ISSUE TITLE
Allow the SAC and asset to be identifiable from events

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-env#691]
To avoid storing a mapping between contract id and the Asset, Horizon needs some way to identify if a contract event was emitted by the SAC, and which asset it belongs to using only the event. @tamirms has a PR that accomplishes this by including the issuer and symbol in the event body [here](https://github.com/stellar/rs-soroban-env/pull/686), but this isn't ideal because it changes the format of the data.

Two alternatives we should explore - 
1. Increase the Bytes limit on topics from 32 and put the asset information in the topics. This will allow consumers to query for the asset information if they'd like, but the body of the data will remain the same.
2. Update the [ContractEvent](https://github.com/stellar/stellar-xdr/blob/df18148747e807618acf4639db41c4fd6f0be9fc/Stellar-ledger.x#L401) xdr to store a SAC type along with asset information. This is more difficult to implement than the first option.

**Comment by paulbellamy** [comment]
> this isn't ideal because it changes the format of the data.

Why is that a problem?

**Comment by sisuresh** [comment]
> > this isn't ideal because it changes the format of the data.
> 
> Why is that a problem?

It special cases events that should be standard. For example, users will have to parse the `transfer` event data differently for the SAC vs a custom WASM token.

**Comment by sisuresh** [comment]
Resolved by https://github.com/stellar/rs-soroban-env/pull/705
