### ISSUE TITLE
Non-diagnostic events are currently unmetered

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#695]
This bug was previously about the event system taking quadratic time due to using MeteredVec. In the meantime this has been changed to be a non-metered standard vector, but this needs to be finished to be metered.

**Comment by jayz22** [comment]
Yeah, I think we discussed before about potentially having a new "mutable metered vector" type. The current `MeteredVector` doesn't make clear distinction the (very important) immutability property. But we previously decided that if we made those events cheap to clone, the quadratic behavior may not be an issue but it makes metering a ton easier. This is no longer the case now with the diagnostic events. 
I will create an issue for the mutable_metered_vector.

**Comment by jayz22** [comment]
Created https://github.com/stellar/rs-soroban-env/issues/707

**Comment by graydon** [comment]
I've updated this to cover the current state of things, which is "non-quadratic vector that's also non-metered". needs metering.
