### ISSUE TITLE
Reconsider (or at least warn about) pointwise growth/change methods

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#696]
Bug https://github.com/stellar/rs-soroban-env/issues/695 presents an issue I've been worried about for a while that I expect we'll see more instances of (either in the host or, more likely, the guest). The host objects for `Vec` and `Map` (and the underlying `MeteredVec` and `MeteredMap` types) have interfaces that _look_ a bit like standard Rust containers, but have radically different performance characteristics (they are all O(N) on the container size).

In general (and @leighmcculloch I would love to hear your thoughts on this) I am feeling like we might want to revisit how we present pointwise "mutating" methods on immutable objects to users. While obviously users will want to pay such costs sometimes (eg. "I really do want to just change an entry in a map, even if it involves cloning the map") in situations where someone's natural instinct is to build up a map or vec incrementally by doing repeated `.set` or `.push` calls, the way these types work is really going to work against performant code, risking making it quadratic.

I'm particularly worried about this in the SDK, which goes out of its way to create the illusion of "mutable objects" by doing this `self.obj = env.copy_and_modify(self.obj, ...)` sort of pattern under the covers.

I wonder if it might be possible to guide users away from such patterns, by surfacing the copying behaviour to users rather than hiding it, and by providing bulk-initialization and vector-concatenation / bulk-map-element-updating as preferred primitives. If you're concerned about users accidentally not noticing a new mutated-copy return value from a copy-and-mutate method, you could have the method consume self and return a new object, or put `#[must_use]` on the function, or similar.

**Comment by leighmcculloch** [comment]
The Vec/Map types have bulk functions already. You can create them with a single call, and you can extend one with another. If there are any bulk functions missing we should definitely add them.

I think .push and .set are still useful, and still required. A dev might need to replace a single value in a Vec and that's it. Or append a single value to a Vec. In both cases there's no reasonable bulk equivalent operation to perform in that use case.

I think to a degree this will be user education.

Note that the existing functions for both types that extend or create from an array use .push under the hood, but that should change once the new host functions are added that let us create from a list.

**Comment by graydon** [comment]
Well, ok. We should do-or-rename this before final --- I still think it might be worth deleting some of these functions entirely since they just ask for misuse -- but if you want to keep them the bug should be renamed to something like "make sure we're using the efficient vector and map ops as much as possible"

**Comment by leighmcculloch** [comment]
I think we harm usability a little too much to make Vec and Map immutable in the SDK. The fact they are immutable in the host is imo an implementation detail.

I don't think we should prevent a user from mutating with a single item because, while I agree someone could use them to do something inefficient, we're making pretty big assumption on the types of things people will want to do with vecs and maps. `push_back(T)` is a reasonable thing to do and may be very efficient if it is the only mutation needed. But, we could revisit the API to simplify it around batched operations.

For example, we could remove the `extend` functions, and replace the `push_back` with a function that can push back anything that can be converted into a Vec<T> iterator. That could include a single item, slice, array, a Vec<T>, so on. It might lead to people doing the best thing more often while not penalizing doing the necessary thing?

As a next step, whichever way we go, I suggest we sketch some possible new APIs.

**Comment by graydon** [comment]
> I think we harm usability a little too much to make Vec and Map immutable in the SDK. The fact they are immutable in the host is imo an implementation detail.

I .. kinda don't agree! It just introduces a new way for users to get confused about aliases. At least immutable things behave the same as single-owner things (which the objects are).

Here's a fundamental question:

```
let mut x = Vec::new(&[5]);
let mut y = x;
x.push(10);
// does the user expect y is [5] or [5,10] here?
```

About half the languages a user might be coming from, they will expect `y` actually also changed. About half they will not. So about half will write a bug based on misunderstanding the semantics! That's a problem, IMO.

If on the other hand we _remove_ the mutating method and make the user do this:

```
let x = Vec::new(&[5]);
let y = x + Vec::new(&[10]);
```

The user can't be confused by aliasing anymore -- obviously `x` is unchanged and `y` has `[5,10]`. As a bonus it also happens to reflect the implementation complexity of operations correctly, which means they won't reach for pointwise methods assuming they amortize growth.

You can still use `x[1]` for read-accessor methods, which I expect a great majority of accesses will be.

The only problem with doing that is that certain operations that do "pointwise replacement" are a bit harder to express with idiomatic operators the way `+` works for building. Probably the best approach is a bunch of separate clone-and-update operators, like `x.clone_with_update(10, z)`

**Comment by graydon** [comment]
Discussed with @leighmcculloch and two points of clarification came out:

  - Wrapper types in SDK are affine, not `Copy`, so the code above can't happen; `x` gets moved to `y` as with a normal Rust container. So the aliasing concern isn't that significant here.
  - There's a nice new set of const-generic APIs on Rust's containers called `get_many` that takes a fixed size set of indices and returns a fixed size set of elements, this might be interesting to copy (and plum through to the bulk-transfer host functions) eg. to amortize iterator loading or such: https://doc.rust-lang.org/std/vec/struct.Vec.html#method.get_many_mut

Leigh also suggested maybe widening the API a bit towards a trait bound, such as taking `IntoVal<Vec<T>>` on mutator methods, so that these all work:

```
.push(&[a]) // single value
.push(&[a, b, c]) // multiple value
.push(&myOtherVec) // multiple value already in a vec
```

Anyway, I'm not overwhelmingly worried about this topic anymore given that the aliasing issue isn't real and users can discover the performance issue on their own. We can probably revisit casually over time, not block a release on it.

**Comment by leighmcculloch** [comment]
I'm more in favor of adding `_many` functions rather than expanding the API of the inputs to the existing functions. Expanding the API with a trait would make it harder to understand what can be passed.

**Comment by leighmcculloch** [comment]
I've opened a new issue for the _many variants, and in conjunction with the other issue already, I think we can address this in the SDK:
- https://github.com/stellar/rs-soroban-sdk/issues/997
- https://github.com/stellar/rs-soroban-sdk/issues/189
- https://github.com/stellar/rs-soroban-sdk/issues/191

**Comment by leighmcculloch** [comment]
I've opened the following issue to address the growth issues with `vec_slice`:
- https://github.com/stellar/rs-soroban-env/issues/696
