### ISSUE TITLE
Limit Soroban `LedgerEntry` size

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/rs-soroban-env#716]
Similar to what we do as a "catch all" to limit transaction size (done outside of env - https://github.com/stellar/stellar-core/issues/3672 ):  we need a limit (network setting) on how big any Soroban ledger entry can get:
while limits on [SCVals](https://github.com/stellar/stellar-protocol/issues/1298) , keys (#629) , etc should be enough, there is a possibility that we miss something (or a combination of things) and that can become a problem for the network over time.

It seems we should be able to enforce this within env, but if not, we should enforce this in the core bridge (when we convert entries into binary blobs when crossing back to C++).

**Comment by jayz22** [comment]
Resolved by https://github.com/stellar/stellar-core/pull/3731.
