### ISSUE TITLE
Naming issue - this module deals with i64, u64, i128, u128 while being names i64

### ISSUE THREAD

**Issue by wildework** [stellar/rs-soroban-env#718]
https://github.com/stellar/rs-soroban-env/blob/5695440da452837555d8f7f259cc33341fdf07b0/soroban-env-common/env.json#L145

This might only affect a few people, but to me it seems like the name of this module export should be `bigint` or something similar that's an umbrella term for `i64`, `u64`, `i128`, `u128`.

**Comment by graydon** [comment]
fixed, this is named `int` now
