### ISSUE TITLE
Support U256/I256 host functions

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#723]

**Comment by tomerweller** [comment]
@jayz22 can you unpack this: what host functions?

**Comment by jayz22** [comment]
Currently we have these types defined and exposed to the user (with conversion functions to and from host values) but there are no host functions allowing the user to do anything with it. They can implement their own U256 arithmetics libs in their contract and use our host functions to transport the values across the env, but this is not scalable (and slower) and we would like to provide native support for such. 

This issue is to provide some basic U256 arithmetics functions such as:
- add, sub, mul, div
- shl, shr
- pow, mod

And possibly conversion to and from bytes.

**Comment by tomerweller** [comment]
Do we have an estimation of how slower it would be doing arithmetics guest side? Could we provide a u256 type in the sdk instead of host functions?

**Comment by jayz22** [comment]
I think we can. I'm not sure how much slower (or if it is indeed slower at all) it will be. I'll do a few experiments and get back to you on this.
