### ISSUE TITLE
Add host functions to transport objects between host and guest memory for `String`, `Timepoint`, `Duration` 

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#724]

**Comment by tomerweller** [comment]
@jayz22 can you unpack this: what are the host functions?

**Comment by jayz22** [comment]
We will add conversion functions between the host object and the guest memory to allow users work with string as bytes. 
We won't be providing string algorithms ( e.g. unicode-related lookups or conversions). This applies to number based types: `Timepoint`, `Duration`.

**Comment by willemneal** [comment]
How about String concatenation? And string interpolation?

**Comment by jayz22** [comment]
We likely won't unless there are strong demands and good reasons for doing them on the host side. Adding sdk functions for those once we have the capabilities to transport the objects into bytes in the guest memory should be straightforward and we might considering doing that.
