### ISSUE TITLE
Revisit diagnostic/debug event design

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-env#731]
Currently, we have three types of host events - 

1. Contract events - metered, hashed into the ledger, and included in tx meta. 
2. Structured debug events - not metered and not hashed into the ledger, but included in tx meta.
3. Debug events - metered, not hashed into the ledger, and not included in tx meta.

Contract and Structured debug events contain xdr::ContractEvents, while Debug events are just strings used for local development.

Some questions we need to answer - 

- [ ] Should Debug events not be metered?
- [ ] If Debug events are not metered, do we combine with Structured debug events and just emit the string in the data field as a byte vector for the existing Debug events.
- [ ] Instead of having events that are not metered, should we treat Structured debug events like Contract events by hashing them into the ledger and therefore including them into the protocol?
- [ ] If we keep non-metered events, should they be put in a separate list from metered events for safety?

**Comment by graydon** [comment]
Done in https://github.com/stellar/rs-soroban-env/pull/806
