### ISSUE TITLE
Reset partial host state between top-level invocations

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#735]

**Comment by dmkozh** [comment]
To expand on this a bit: we should probably reset budget after (or before) every contract invocation. It's probably also a good idea to reset the footprint as well. This way the users will be able to get both metering data and footprint data concerning only a single interesting invocation vs getting whatever has been accumulated before.

**Comment by jayz22** [comment]
Add the original PR comment for a bit more context. https://github.com/stellar/rs-soroban-env/pull/704#discussion_r1139467147

**Comment by leighmcculloch** [comment]
> every contract invocation

Every top-level contract invocation. For sub-invocations we shouldn't fiddle with the state I don't think.

**Comment by dmkozh** [comment]
> Every top-level contract invocation. For sub-invocations we shouldn't fiddle with the state I don't think.

Yeah, definitely. Currently we only reset the auth manager when we pop the last frame. Instead, we should probably reset auth, budget and events when we push the first frame into stack. This will make sure that everything is clean when the contract is called (unlike auth budget is affected by pretty much any `Env` calls outside of any contracts/frames).

**Comment by jayz22** [comment]
We (cc @dmkozh @graydon) discussed this issue in our planning meeting, here is a summary. 
Resetting a subset host state (e.g. auth, budget, events) is necessary for user tests, i.e. users setting up multiple contract invocations using the SDK, because users want better metrics and state-reporting that are isolated for different invocations. 
The benefits of doing that for internal tests, which is what this issue is originally about, is less clear. Automatically resetting partial host state based on the host's stack size may produce unwanted side effects and confusions (the budget is supposed to outlive the host in real invocation).
So we think the better fix is on the SDK side, making the `internal::Env` more granular and allowing automatic reset of certain components between top-invocations. @leighmcculloch does this approach make sense? @dmkozh is there a similar SDK issue already or do we need to create one?

**Comment by dmkozh** [comment]
https://github.com/stellar/rs-soroban-sdk/issues/1113 is the related issue.

**Comment by jayz22** [comment]
Closing as per above.
