### ISSUE TITLE
Auth Next: Allow contracts to authorize subcontract calls

### ISSUE THREAD

**Issue by dmkozh** [stellar/rs-soroban-env#744]
Currently there is an inconsistency in the auth framework where accounts can authorize arbitrary call trees via signing them, but contracts only implicitly authorize the sub-contract calls, but nothing else. So, for example, the `xfer` call can't be performed on behalf of the invoker contract. While this case is not as frequent as account-based authorizations, it still might appear in practice (e.g. when sub-contract needs to safely pull token from the invoker contract).

Potential solutions are:
- Provide a host function that adds sub-call authorizations for the next contract call
- Add a version of the contract call function that accepts additional sub-contract authorizations

**Comment by mootz12** [comment]
Wanted to add some context about why a solution to this inconsistency is important to have for Soroban.

Consider any vault contract (like DAI, [xcyloans](https://github.com/xycloo/xycloans/tree/main/flash-loan-vault), or a Blend lending pool) that contains a function that, from an Address, attempts to transfer funds into it using the `auth-next` pattern:

```rust
fn vault_deposit(env: Env, from: Address, amount: i128) {
    from.require_auth(); // check from has signed off on depositing funds
    // ... some contract specific logic
    let token_client = // whatever token is being deposited
    token_client.xfer(&from, &env.current_contract_address(), &amount); // contains an underlying call to `require_auth` for `from`
    // ... some contract specific logic
}
```

Contracts (like a DAO attempting to lend funds, or a smart wallet) would not be able to call this deposit function without the implementation of this feature.

This could push contract designers to expose two functions, one with approval logic for contracts, and one with auth-next logic for users (or anyone who can add signatures to the call tree). Another option would for them to only expose the approval based function and not support auth-next in favor of allowing contracts to use their protocol.
