### ISSUE TITLE
Clarify that length refers to number of RawVals

### ISSUE THREAD

**Issue by wildework** [stellar/rs-soroban-env#749]
The vector module method `vec_new_from_linear_memory` takes two arguments. Both relate to linear memory. The string and byte modules have similar init methods `_from_linear_memory`, in those cases `len` always refers to the number of bytes to read. In the case of `vec_new_from_linear_memory` it's actually the number of `RawVal` elements and they take up 8 bytes each (being 64 bit numbers).

I believe we should either change the docs to make that explicit, or have `len` return the number of bytes to read from linear memory.

https://github.com/stellar/rs-soroban-env/blob/aa7424dc2ea8db1391365e229f550d726734ae55/soroban-env-common/env.json#L766

**Comment by graydon** [comment]
Agree the docs should be clear, but the count should remain element count not byte count.
