### ISSUE TITLE
Add host function to install a contract 

### ISSUE THREAD

**Issue by willemneal** [stellar/rs-soroban-env#757]
### What problem does your feature solve?

I'm currently working on a [publishing contract for publishing and versioning installed binaries](https://github.com/TENK-DAO/smart-deploy). However, it still requires that the binary was installed before being published.  This means that a hash could be published that doesn't correspond to an installed binary.

### What would you like to see?

A host function that would let the contract install bytes.  This would allow the contract to ensure that a published hash corresponds to an installed contract.

**Comment by dmkozh** [comment]
I was never a huge fan of this, but it seems like if the Wasm blob comes as a tx input it does make sense to allow doing the upload from within the contract code.

**Comment by dmkozh** [comment]
This is done now.
