### ISSUE TITLE
CLI: Better error messages for auth violation

### ISSUE THREAD

**Issue by willemneal** [stellar/rs-soroban-env#760]
### What problem does your feature solve?

Currently the error message returned with improper permissions is:

```
error: HostError
Value: Status(HostStorageError(AccessToUnknownEntry))

Backtrace (newest first):
   0: backtrace::capture::Backtrace::new_unresolved
   1: <&soroban_ledger_snapshot::LedgerSnapshot as soroban_env_host::storage::SnapshotSource>::get
   2: <soroban_ledger_snapshot::LedgerSnapshot as soroban_env_host::storage::SnapshotSource>::get
   3: soroban_env_host::storage::Storage::get
   4: soroban_env_host::host::data_helper::<impl soroban_env_host::host::Host>::load_account
   5: soroban_env_host::auth::AuthorizationManager::maybe_emulate_authentication
   6: soroban_env_host::host::Host::pop_frame
   7: soroban_env_host::host::Host::invoke_function
   8: soroban_cli::commands::contract::invoke::Cmd::run_in_sandbox
   9: soroban_cli::commands::contract::Cmd::run::{{closure}}
  10: soroban_cli::commands::Root::run::{{closure}}
  11: tokio::runtime::park::CachedParkThread::block_on
  12: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  13: soroban::main
  ```

This isn't clear where the failure is coming from.

### What would you like to see?

Specifics about the violation.  E.g. ` Address "X" does not have permission to invoke this method`

**Comment by leighmcculloch** [comment]
I've transferred this issue to `stellar/rs-soroban-env`.

**Comment by dmkozh** [comment]
There is no auth violation here and the call stack points at the actual error, which is the account missing from the snapshot source. Authorization errors have the respective error codes, but there are other errors that may occur on the auth code paths (e.g. running out of budget, or accessing an entry outside of the footprint etc.), which will be reported with the corresponding messages/debug events.
