### ISSUE TITLE
Auth: No Frame when errors occur during auth

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#768]
I've noticed that when `require_auth` is called from the SDK, and enforcing auth is enabled, if any error is encountered during the require_auth logic, the errors that get shown in the backtrace indicate something is wrong with the setup of the host:

```
Debug events (newest first):
   0: "Debug escalating error '' to panic"
   1: "Debug contract call invocation resulted in error Status(HostAuthError(NotAuthorized))"
   2: "Debug caught panic from contract function 'Symbol(add)', propagating escalated error 'Status(HostAuthError(NotAuthorized))'"
   3: "Debug escalating error '' to panic"
   4: "Debug no frames to derive the invoker from"
```

The lines of interest are 0, 3 and 4.

Lines 0 and 3 show empty strings for an error being escalated. Somewhere in the host we're generating an error without a description, which we should fix and give it an appropriate description.

Line 4 indicates that there's no frame to pull the invoker from, which is surprising because inside a contract call there is definitely a frame.

cc @sisuresh @dmkozh

**Comment by leighmcculloch** [comment]
The shortest path to replicating this issue is to write a contract in the SDK that uses `require_auth`, and comment out the SDK line that enables recording auth.

Example contract:

```rust
#![no_std]
use soroban_sdk::{contracterror, contractimpl, vec, Address, Env, RawVal};

pub struct Contract;

#[contractimpl]
impl Contract {
    pub fn add(e: Env, a: Address) -> u64 {
        a.require_auth();
        2
    }
}


#[cfg(test)]
mod test {
    use soroban_sdk::{
        testutils::Address as _,
        Address, Env,
    };

    use crate::{Authonator, Contract, ContractClient};
    extern crate std;

    #[test]
    fn test_add() {
        let e = Env::default();
        let contract_id = e.register_contract(None, Contract);
        let client = ContractClient::new(&e, &contract_id);
        let a = Address::random();
        let r = client.add(&a);
        assert_eq!(r, 2);
    }
}

```

Line to comment out in SDK to enable auth enforcing:

https://github.com/stellar/rs-soroban-sdk/blob/6a1f0fecc8fba0138394382290e3e88807454b4f/soroban-sdk/src/env.rs#L485

**Comment by leighmcculloch** [comment]
Related conversation that occurred in Slack: https://stellarfoundation.slack.com/archives/C030Z9EHVQE/p1681937681931139

**Comment by dmkozh** [comment]
> Line 4 indicates that there's no frame to pull the invoker from, which is surprising because inside a contract call there is definitely a frame.

There is no invoker contract for root contract in tests (which is what auth is looking for). That's not an actual error - we need to clean up the code that gets the invoker contract id, as it always produces the debug event now even if the failure is handled gracefully (like in auth).

The actual error here is ` Status(HostAuthError(NotAuthorized))` which means that the address hasn't authorized the invocation, more precisely that there is no matching auth tree for the address.
