### ISSUE TITLE
Debug events are ambiguous as to which contract generated them

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#772]
Debug events when output do not include a clear indication of which contract ID generated the event. This can get ambiguous with even small traces involving only a couple contracts. For example:

```
HostError
Value: Status(ContractError(5))

Debug events (newest first):
   0: "Debug escalating error '' to panic"
   1: "Debug contract call invocation resulted in error Status(ContractError(5))"
   2: "Debug caught panic from contract function 'Symbol(add)', propagating escalated error 'Status(ContractError(5))'"
   3: "Debug escalating error '' to panic"
   4: "Debug incompatible signature format"
```

(This log is from #771.)

Could we include contract IDs, or truncated contract IDs in debug events?

cc @graydon

**Comment by graydon** [comment]
Agreed. This goes together with https://github.com/stellar/rs-soroban-env/issues/681 IMO, we should just have objects kicking around for any contract ID that we can tag anything with that is contract-ID-specific.

(Possibly the object handles for contract IDs can/should be related to the ticket numbers in https://github.com/stellar/rs-soroban-env/pull/132 -- if we're never rolling back object handles it might make sense to assign ticket numbers as "the next free object handle" when pushing a frame)

**Comment by graydon** [comment]
implemented in https://github.com/stellar/stellar-xdr/pull/92 -- should land soon

**Comment by graydon** [comment]
Done in https://github.com/stellar/rs-soroban-env/pull/806
