### ISSUE TITLE
Auth: Ability to snapshot and restore authorization state

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#785]
The SDK sets authorization state sometimes temporarily for a single invocation. To create a better developer experience by allowing the developer to set temporary authorization state, it would be ideal if the host provided a way to snapshot authorization, and then allow restoring it.

The use case would be that a developer might temporarily mock for a single invocation, and their expectation will be that the mock is gone after that invocation.

The authorization state types in the host are all pub(crate) and for the sake of maintenance we can avoid making them part of the public API. We can introduce a snapshot type that can store a copy of the state, and make only that opaque snapshot type public.

Related discussion https://discord.com/channels/897514728459468821/1101645967608008826

**Comment by dmkozh** [comment]
This should be possible in preview 10 via test-only functions `snapshot_auth_manager` and `set_auth_manager`.

**Comment by leighmcculloch** [comment]
The following issue has been opened upstream to utilize it:
- https://github.com/stellar/rs-soroban-sdk/issues/1084
