### ISSUE TITLE
Auth: sub-auths containing auth with different args for same address are not verified

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#788]
Auth that involves multiple calls to require_auth with the same address but different args at each level, for a custom contract providing the auth, appears to have a bug.

When I call contract B, which calls contract A, with an auth contract that will only approve once, the entire invocation succeeds and the auth contract is called only once. This is even in the case that require_auth occurs with different args.

I expect the contract auth contract should have been called twice. There are different sets of args, and the auth contract should be given the opportunity to verify the second authorization and its inputs.

```rust
#[contractimpl]
impl ContractA {
    pub fn fn1(a: Address) -> u64 {
        a.require_auth();
        2
    }
}
```

```rust
#[contractimpl]
impl ContractB {
    pub fn fn2(e: Env, a: Address, sub: BytesN<32>) -> u64 {
        a.require_auth_for_args((1, 2).into_val(&e));
        let client = ContractAClient::new(&e, &sub);
        client.fn1(&a)
    }
}
```

The auth contract I'm using is:

```rust

    mod auth_approve_once {
        use super::*;

        pub struct Contract;

        #[contracterror]
        #[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
        #[repr(u32)]
        pub enum Error {
            Decline = 1,
        }

        #[contractimpl]
        impl Contract {
            const COUNT: Symbol = Symbol::short("COUNT");

            #[allow(non_snake_case)]
            pub fn __check_auth(
                e: Env,
                _signature_payload: RawVal,
                _signatures: RawVal,
                _auth_context: RawVal,
            ) -> Result<(), Error> {
                let count = e.storage().get(&Self::COUNT).unwrap_or(Ok(0)).unwrap();
                if count > 0 {
                    Err(Error::Decline)
                } else {
                    e.storage().set(&Self::COUNT, &(count + 1));
                    Ok(())
                }
            }
        }
    }
```

This is occurring with env at commit efffbbb.

cc @dmkozh

**Comment by leighmcculloch** [comment]
[Diagram](https://mermaid.live/edit#pako:eNqNUcFKA0EM_ZUwJ8Wt2EIR51DYrRcPnrwOSJxJ26G7mZqdLUjp0ZufoD_XLzG7FmpvvYTh5SXvZd7O-BTIWNPSe0fs6THiUrBx7HiDkqOPG-QMFWAL5Tk277HqHCsHsOzyCuaJs6DPjrXELWbqyRWMZrMb5VkQlYxCr9izMQSxCCjL1o6LiWPdNFLqCCoLh-_P3tBxVkefeJvW1GNCPoMs364m02kB4zstD_fXjucX6OA_FeUdfr4cc1KfNS0ypMUwfXYLaBs81jWFW8fEobcwSJ18BjrdawrTkDQYg37xzjGAM3lFDTlj9RlQ1s443itP3aWXD_bGZumoMN0m6IpjHMYusG4VpRBzkue_zIbo9r9ZGZdM) of the expected flow. The step that I expected to occur, but isn't, is highlighted in red.

<img width="1058" alt="Screenshot 2023-05-01 at 12 59 36 PM" src="https://user-images.githubusercontent.com/351529/235520863-14a68a78-9da5-49d6-a54b-7e831f910d7c.png">

**Comment by dmkozh** [comment]
This is expected. The account contract is called once *per tree*, not per `require_auth` (i.e. the authorization unit is the whole tree).  All the calls that are being authorized are exposed to the account contract, which we use e.g. here: https://github.com/stellar/soroban-examples/blob/main/account/src/lib.rs#L153

Host ensures the integrity between the arguments of `__check_auth` calls and the actual `require_auth` calls, so e.g. if your account contract approves `transfer(contract, 1 USD)`, a call to `transfer(contract, 100 usd)` will fail. Hence we can 'front-load' the verification for the whole context.

**Comment by leighmcculloch** [comment]
Got it, so the `auth_context` parameter on auth contracts is actually multiple contexts, one for each `require_auth` call?

**Comment by dmkozh** [comment]
> Got it, so the auth_context parameter on auth contracts is actually multiple contexts, one for each require_auth call?

It is a vector of the tree nodes (very similar to your changes to the recording mode) in a single authorized tree (which is also what is being signed when sending a tx). I'm not passing a tree here for similar reasons to the recording mode - it would probably be daunting to walk a tree to enforce the policy. Though maybe it could still be a tree, not 100% sure (I've been thinking that having the whole tree is not super useful - the root is the first argument and it's probably enough for most of the time).
