### ISSUE TITLE
Auth: duplicate auths are allowed sometimes leading to inconsistent auth behavior depending on caller

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#795]
If a contract is defined with duplicate auths, and that contract is called with a call tree where that contract is the first contract to validate an address, then the duplicate auths are allowed because each auth is in fact their own auth call tree independent from each other.

If a contract is defined with duplicate auths, and that contract is called with a call tree where the address is also required of auth in a calling contract, then the duplicate auths are not allowed because they exist in the same authorization call tree.

For example, the following is a minimal reproduction of a contract contains duplicate auth.

```rust
#[contractimpl]
impl ContractB {
    pub fn f(a: Address) -> i32 {
        a.require_auth();
        a.require_auth();
        1
    }
}
```

The host has an error `DuplicateAuthorization` that will be returned when duplicate auths are detected in the same authorization call tree.

This behavior can make it possible to develop a contract that seems like it is working fine, but then isn't when called by another contract that also authorizes the address.

The chance of someone triggering this behavior is low given that duplicate auths are not expected. However, this could show up if libraries provide auth and applications also do auth alongside the library.

**Comment by leighmcculloch** [comment]
The main concern with this bug is that contract auth behaves differently when a contract is called directly vs called via another contract, in a way that is not intuitive or obvious.

I think this issue has two actions we need to take:

1. Plug this difference so auth behaves the same in both situations.

2. Investigate what about the architecture and structure of auth has brought this difference about, because if the structure of how auth is implemented has led to differences in auth behavior, there could be others or it could lead to others during maintenance.

**Comment by dmkozh** [comment]
I've introduced this error to avoid tree matching ambiguity, but now it seems to me like that was not necessary. I'll experiment with this - probably we just don't need this error altogether.

Note though, that it doesn't seem like breakage is possible in your scenario. The duplicate auths have to be exactly duplicate, i.e. they must map to the same authorized paths with the same args.  So you should be calling `require_auth` for the same address with the same arguments within the same stack frame. That said, it still could happen (e.g. in the multiswap example a user might in theory sign two identical swaps). So probably it's simpler to just allow this to avoid inconcistencies.

**Comment by dmkozh** [comment]
This should be fixed now - we allow duplicate `require_auth` calls each of which has to belong to a separate authorized call tree.
