### ISSUE TITLE
Auth: auths in call trees are sometimes optional

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#800]
Clients are allowed to include auth invocations that when they aren't needed by the contracts, and other times their extra presence causes an error. Similar to #795 this difference in behavior is concerning because there isn't a naturally occurring reason for the user for why extra auths are sometimes allowed to be present, and in other times not.

For example, the following test passes. The contracts don't require any signatures, but some are provided. The fact they are provided does seem to cause a problem.

```rust
use crate as soroban_sdk;

use soroban_sdk::{
    contractimpl,
    testutils::{Address as _, MockAuth, MockAuthInvoke},
    Address, BytesN, Env, IntoVal,
};

pub struct ContractA;

#[contractimpl]
impl ContractA {
    pub fn fna(e: Env, contract: BytesN<32>, a: Address, b: Address) -> i32 {
        let client = ContractBClient::new(&e, &contract);
        client.fnb(&a, &b)
    }
}

pub struct ContractB;

#[contractimpl]
impl ContractB {
    pub fn fnb(a: Address, b: Address) -> i32 {
        1
    }
}

#[test]
fn test() {
    let e = Env::default();
    let contract_a_id = e.register_contract(None, ContractA);
    let contract_b_id = e.register_contract(None, ContractB);
    let client = ContractAClient::new(&e, &contract_a_id);

    let a = Address::random(&e);
    let b = Address::random(&e);

    let c = client
        .mock_auths(&[
            MockAuth {
                address: &a,
                nonce: 0,
                invoke: &MockAuthInvoke {
                    contract: &contract_a_id,
                    fn_name: "fna",
                    args: ().into_val(&e),
                    sub_invokes: &[MockAuthInvoke {
                        contract: &contract_b_id,
                        fn_name: "fnb",
                        args: (&a, &b).into_val(&e),
                        sub_invokes: &[],
                    }],
                },
            },
        ])
        .fna(&contract_b_id, &a, &b);

    assert_eq!(c, 1);

    println!("{:?}", e.auths());
}
```

If we make one change, adding in verification of `a`'s auth into contract `B`, the test fails, even though the test is providing a valid signed auth invocation for that `require_auth` call. The test is providing the extra auth for `a` in contract `A` that was allowed before, but isn't now.

```diff
@@ -21,6 +21,7 @@ pub struct ContractB;
 #[contractimpl]
 impl ContractB {
     pub fn fnb(a: Address, b: Address) -> i32 {
+        a.require_auth();
         1
     }
 }
```

If we make another change, adding in a `require_auth` call into contract `A` for the same address `a`, the test passes again.

```diff
@@ -11,6 +11,7 @@ pub struct ContractA;
 #[contractimpl]
 impl ContractA {
     pub fn fna(e: Env, contract: BytesN<32>, a: Address, b: Address) -> i32 {
+        a.require_auth_for_args(().into_val(&e));
         let client = ContractBClient::new(&e, &contract);
         client.fnb(&a, &b)
     }
```

---

Examples are using stellar/rs-soroban-sdk@cf527d0.

Examples use `mock_auth` to setup auth, but those mock auths are real authorizations that are being setup, so real auth like the auth on a deployed network is being used. The "mocking" is a custom contract that just approves any require auth for the address.

**Comment by dmkozh** [comment]
This is the expected behavior - we don't allow a tree signature to be used in a context where a single call is expected (e.g. you don't want your LP trade signature to be used to just transfer the token without performing a trade).
