### ISSUE TITLE
Testutils is nondeterministic

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#810]
There are some testutils methods that access thread_rng and are therefore nondeterministic. In general in core we prefer all tests to have fairly rigid determinism and, if they want "quasi nondeterminism", to use a special-purpose seed that's slow-changing (eg. once a day) to make debugging sessions even on that quasi-nondeterminism stable.

But in general most of the paths I'm seeing under testutils would be fine with a constant-seeded PRNG, so I would generally prefer that.

**Comment by graydon** [comment]
(Might be worth checking if these cases can use the newly-added host PRNG)

**Comment by anupsdf** [comment]
Setting target milestone to `Post testnet` after discussing with @graydon

**Comment by graydon** [comment]
This was ultimately fixed in https://github.com/stellar/rs-soroban-env/pull/1124
