### ISSUE TITLE
dynamic borrows can panic

### ISSUE THREAD

**Issue by graydon** [stellar/rs-soroban-env#817]
there are a bunch of elements of the host structure held in refcells which we dynamically borrow when mutating them. in theory there shouldn't be any code paths that cause these to fail; but in practice it's possible to have (and recent changes have occasionally introduced) a path that reborrows something already borrowed, eg. mutating the object table while it's being read-borrowed. this currently causes a panic. we should change these to use `try` variants that fail with an internal error rather than panic.

**Comment by anupsdf** [comment]
Setting target milestone to `Testnet Phase 1` after discussing with @graydon
