### ISSUE TITLE
Change all Bytes for contract IDs to Address

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#818]
We need to change the host interface so that contract IDs are always communicated as an `AddressObject` instead of a `BytesObject`.

In https://github.com/stellar/rs-soroban-sdk/pull/947 we changed the way that the SDK externalizes contract IDs, so that they are wherever possible externalized as an `Address`. The SDK does a conversion from bytes to address and vice-versa to make that happen.

The conversions aren't expensive, but ideally the host would just always provide contract IDs as addresses since that is how the SDK externalizes it to contracts.

This change will require changing the types of values passed to or from many host functions. The SDK will need to be updated after this change is made.

**Comment by jayz22** [comment]
Resolved by https://github.com/stellar/rs-soroban-env/pull/853. Only found one residual function `get_invoking_contract` and cleaned it up.

**Comment by leighmcculloch** [comment]
@jayz22 There are other places I think, such as call stacks, and anywhere in auth a contract ID is specified. Maybe these were already cleaned up though. cc @dmkozh

**Comment by jayz22** [comment]
The `get_current_call_stack` returns a Vector of `(RawVal, RawVal)`, with the contract id is stored as `Bytes` in the first RawVal. So I thought it was pretty much internal detail. But it's more consistent to change to Address too. I will clean this up.
All the external host functions I checked have contract ID specified as `AddressObject` already, internally it might still be referring to the `Hash` part (such as `vm.contract_id`) which should be okay. 
Reopening it to fix `get_current_call_stack` and any other ones that pop up.

**Comment by jayz22** [comment]
https://github.com/stellar/rs-soroban-env/pull/866 fixed the `get_current_call_stack`. 
As far as I can tell this completes makes all the host interface work with `AddressObject`. If I missed any thing, feel free to reopen this.
