### ISSUE TITLE
Metering closure call

### ISSUE THREAD

**Issue by anupsdf** [stellar/rs-soroban-env#829]
### What?
I noticed comments in the code regarding metering the calls to closures. 
example: [host_object.rs](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/host_object.rs#LL207C14-L207C14)
Creating this tracking issue to address this.

### What did you expect to see?
Metering the closures.

**Comment by graydon** [comment]
This comment is not 100% clear but what it's really getting at is "whatever happens in the body of the closure passed in needs to have metering itself, the higher order function here that takes the closure isn't magically able to look inside to tell what it does". But the call sites that lead to here all pass closures that do metering of their bodies, as far as I know (I did a quick look over calls to `visit_obj` which is what leads here) so .. unless you see a case where that's not happening, the general fact that "metering has to happen in the closures" isn't a bug, it's just an requirement of callers.

(In general it's fairly hard to be certain that "everything that needs to be metered is metered", I'm not saying "we didn't miss anything", I'm just saying "this particular function taking a closure does not mean there's something missing from this function". If there was something missing it'd be in one of the _specific_ closures passed to this function.)
