### ISSUE TITLE
Update HOST_FUNCTION_TYPE_INVOKE_CONTRACT to specify contract ID and function name with their actual types

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-env#859]
For example, if the contract id type is incorrect, you'll get [this](https://github.com/stellar/rs-soroban-env/blob/e6e02dc4b5cf946028e51603883bd81ca38ce519/soroban-env-host/src/host/frame.rs#L636) error about "unexpected number of arguments", but it's actually a type error.

**Comment by leighmcculloch** [comment]
Can we make the types that are static the actual types instead? e.g. Instead of ScVal for the address, make it an ScAddress.

**Comment by sisuresh** [comment]
Yeah we should update https://github.com/stellar/stellar-xdr/blob/18437a90b3b9962b22b99ce153bd5abfe3688fba/Stellar-transaction.x#L508 to separate out the contract id and function name from the args and use their actual types.

**Comment by dmkozh** [comment]
I would also consider using `SCVal args<>` instead of `ScVec args;`, as `SCVec` is not used much in top-level APIs and there is no longer any XDR limit on `SCVec` size.

**Comment by dmkozh** [comment]
This also allows us to get rid of `SorobanAuthorizedContractFunction` as it will be equivalent to the struct we use to invoke the host fn (which will make auth more consistent with what's being invoked).
