### ISSUE TITLE
Add contract instance data storage type

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#860]
Contract instance data has come up many times for different reasons. Most of those needs have evaporated, except for the need to simplify rent maintenance and entry loading costs for repeatedly used common data.

Contract instance data would be contract data stored in a key-value map inside the contract instance, and therefore rent bumped with the instance, and always loaded with the instance meaning no additional footprints would be required.

Discussion in Discord is at: https://discord.com/channels/897514728459468821/1119327246902120550

**Comment by sisuresh** [comment]
Closed by https://github.com/stellar/rs-soroban-env/pull/886
