### ISSUE TITLE
Implement RestoreFootprintOp

### ISSUE THREAD

**Issue by SirTyson** [stellar/rs-soroban-env#863]
We need to implement `RestoreFootprintOp`. This op should follow a similar interface to `BumpFootprintExpirationOp`. The user should be able to specify a set of keys for `Persistent` entries that have expired. An expired entry is any entry such that `last_closed_ledger >= entry.expirationLedger`. It does not matter if the entry has expired but is still in the BucketList or if the entry has been evicted and sent to the ESS, this operation will restore the entry.

The restored entries should have the minimum required expirationLedger after they are restored. We should charge write fees, lifetime extension fees, and some instruction fees for the restoration.

**Comment by leighmcculloch** [comment]
`RestoreOp` => `RestoreFootprintOp`

Discussion: https://discord.com/channels/897514728459468821/1118690059374313593/1119389842032300083

**Comment by sisuresh** [comment]
Closed by https://github.com/stellar/stellar-core/pull/3793
