### ISSUE TITLE
Record side effect signatures from tests

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/rs-soroban-env#872]
Similar to what we do in the C++ tests, we should record the side effects that tests have when interacting with the host.
This allows to catch bugs such as:
* determinism issues due to dependency on prng
* unintended behavior changes

**Comment by MonsieurNicolas** [comment]
This is the host counterpart to https://github.com/stellar/rs-soroban-sdk/issues/414 (that allows any contract to do the same)

**Comment by graydon** [comment]
this should include everything _observable_ even if it's not commonly observed or emitted in meta (all ledger changes and footprints, content of auth structures, content of budget, contents of host object table, content of PRNG, content of every VM's linear memory).

**Comment by graydon** [comment]
https://github.com/stellar/rs-soroban-env/pull/1142 has an initial cut

**Comment by graydon** [comment]
Merged #1142, we can continue to iterate on this
