### ISSUE TITLE
Make some host errors non-recoverable

### ISSUE THREAD

**Issue by dmkozh** [stellar/rs-soroban-env#876]
Currently `try_call` allows recovering from all the host errors, including some 'system' errors, like running out of budget or accessing entry outside of the footprint. We should make this more or less consistent with host function recovery (i.e. if a contract can't recover from an error, `try_call` should not recover from such error either).

The benefit of ensuring failure for such scenarios is beneficial for the users of Soroban auth - the whole transaction will be rolled back and no nonces will be consumed, so the sender could re-submit the new transaction without regenerating soroban signatures.

https://discord.com/channels/897514728459468821/1119364291615793162

**Comment by jayz22** [comment]
Just wanted to clarify my understanding from reading that thread. If a transaction fail, the account seq num gets consumed and the transaction cannot be resubmitted. Here you mean create a new transaction with the same auth (which can be recovered if transaction fails) and re-submit it?

**Comment by dmkozh** [comment]
Yes. Sequence number has to be consumed (to pay fees), but soroban auth payload will remain usable.
