### ISSUE TITLE
Secp256k1: consider switching to a cheaper implementation 

### ISSUE THREAD

**Issue by tomerweller** [stellar/rs-soroban-env#902]
The current const cpu cost of the secp256k1 recover function is 2,319,640. That is ~6.3x than that of the ed25519 verify function which is 369,634.

https://github.com/stellar/rs-soroban-env/pull/839#issuecomment-1592192059 suggests that switching implementation from `k256` to `secp256k1` can reduce the cost by ~5x.

**Comment by graydon** [comment]
Based on [comments in the linked bug](https://github.com/stellar/rs-soroban-env/pull/839#issuecomment-1592348975) we're not going to do this for now. It's 2x perf plus 2x for checking-its-work (a safety step!) and the other option has had some scary memory errors in the bindings. If someone is really struggling under the costs we can revisit.
