### ISSUE TITLE
[Test] For any host bug where tracker_by_address_handle was not reset

### ISSUE THREAD

**Issue by anupsdf** [stellar/rs-soroban-env#906]
Write test for any host bug where tracker_by_address_handle was not reset.
More discussion [here](https://github.com/stellar/rs-soroban-env/pull/645#discussion_r1094874829).

**Comment by dmkozh** [comment]
The linked thread is about an issue that concerned only tests and recording mode. The recording mode is covered in tests now and test-only functionality is covered naturally in SDK/example tests.
