### ISSUE TITLE
[Test] Write test for duplicate AuthorizedInvocations in a contract

### ISSUE THREAD

**Issue by anupsdf** [stellar/rs-soroban-env#907]
[Test] Write test for duplicate AuthorizedInvocations in a contract

**Comment by dmkozh** [comment]
I'm not sure what is this about exactly; there are tests for various `require_auth` combinations. `AuthorizedInvocation` doesn't exist in contract at all. I think we can cover this additionally in the core tests (so that transaction fields are covered as well).

**Comment by dmkozh** [comment]
I think it's worth building upon #909 and try passing extra auth XDR that shouldn't be used (this is covered on the env side, but would be nice to make sure it works e2e)
