### ISSUE TITLE
[Test] Write test to verify all trustline and issuer semantics

### ISSUE THREAD

**Issue by anupsdf** [stellar/rs-soroban-env#911]
Write tests to verify all trustline and issuer semantics are followed. For example, clawback, auth_immutable, auth_required,  etc….
Have tests for,
- [ ] For both account 
- [ ] Non account addresses.
- [ ] Auth required tests.

**Comment by sisuresh** [comment]
`test_clawback_on_account` and `test_clawback_on_contract`  covers both clawback balance cases.
