### ISSUE TITLE
[Test] Verify that diagnostic events are not metered

### ISSUE THREAD

**Issue by anupsdf** [stellar/rs-soroban-env#916]
[Test] Verify that diagnostic events are not metered

**Comment by jayz22** [comment]
Resolved by https://github.com/stellar/rs-soroban-env/pull/1189.
We also have a fuzzing test https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/fuzz/fuzz_targets/log_from_linear_memory.rs that tests diagnostic logging produces no effect on the production budget with random inputs.
