### ISSUE TITLE
[Test] Verify that failed invocation does not emit events in core

### ISSUE THREAD

**Issue by anupsdf** [stellar/rs-soroban-env#917]
[Test] Verify that failed invocation does not emit events in core.

- [ ] InvokeHostFunctionOp
- [ ] Test that DiagnosticEvents do emit events

**Comment by sisuresh** [comment]
Bump and restore ops don't emit events, so I removed them from the list.

**Comment by sisuresh** [comment]
Closed by https://github.com/stellar/stellar-core/pull/4096
