### ISSUE TITLE
[Test] Write tests for InvokeHostFunctionOp

### ISSUE THREAD

**Issue by anupsdf** [stellar/rs-soroban-env#919]
[Test] Write tests for InvokeHostFunctionOp,

- [ ] Unused key in read set
- [ ] Unused key in readwrite set
- [ ] Delete/update key in read set
- [ ] Delete/update key not in any set

Pass invalid entries in footprint and make sure we fail gracefully.
- [ ] Invalid Trustlines
- [ ] Data
- [ ] Offer

**Comment by sisuresh** [comment]
Closed by https://github.com/stellar/stellar-core/pull/3858
