### ISSUE TITLE
[Test] Restoration of config upgrades 

### ISSUE THREAD

**Issue by anupsdf** [stellar/rs-soroban-env#921]
Write test for Restoration of config upgrades. 

For example, this [test](https://github.com/dmkozh/stellar-core/blob/169f7e0afe58e713c9ea50821cf8bd8d8b943f01/src/herder/test/UpgradesTests.cpp#L2797) to restore upgrades did not work because assumeStateWork in LedgerManagerImpl ends up being null. We can investigate this.

**Comment by SirTyson** [comment]
Closing, config upgrades have been switched to TEMPORARY so they are not restorable. #3990 adds tests enforcing config upgrade lifetimes.
