### ISSUE TITLE
Remove contract event topic limits 

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#958]
We have a few limits in the contract event [topics](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/host/validity.rs#L119):
- No. topics <= 4
- Topic byte size  < 64

These were some arbitrary limits put there initially, but are no longer needed. They are also not enforced consistently (diagnostic event contains a `ContractEvent` but we don't check that limit). Contract events are hashed into the transaction result, ~both contract and diagnostic~ contract events are included in the meta and is subject to limits and fees.

**Comment by jayz22** [comment]
On second thought, these limits should not apply to diagnostic events (the current behavior is correct), since diagnostic events should be infallible (see https://github.com/stellar/rs-soroban-env/issues/962 to validate that).

**Comment by jayz22** [comment]
I think it is necessary to more clearly spell out the event limits. 
- number of topics
- single topic size limit
- data size limit
Without these limits, contracts may DOS the downstream system by submitting many large events (each up to the metadata size limit). 

The CAP also needs to be updated with the limits (https://github.com/stellar/stellar-protocol/pull/1371).

**Comment by sisuresh** [comment]
The 4 limit was chosen arbitrarily since that's the limit of topics in the evm. We don't need to follow that though because the topics are not indexed in the protocol like in Ethereum.

**Comment by jayz22** [comment]
Based on recent discussions, downstream are more concerned with the meta data size to maintain than the number of topics. Thus we've decided to move the topics limit. 
The meta size limit has been repurposed to event size limit in https://github.com/stellar/stellar-xdr/pull/127/files, and will be set to a much lower value ~10k to limit the downstream impact.
