### ISSUE TITLE
[Test] verify that diagnostic events cannot fail

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#962]
Diagnostic events are non-metered, not part of the protocol. So if they fail, they will trigger the error path, which will cause validators different behaviors depending on whether diagnostics are enabled or not. 
We should test/audit all the diagnostic event generating paths to make sure they are infallible. 
cc @sisuresh

**Comment by sisuresh** [comment]
yeah this is something @dmkozh also mentioned to me recently. We should just swallow errors instead of propagating them.

**Comment by jayz22** [comment]
Resolved by https://github.com/stellar/rs-soroban-env/pull/1123 and https://github.com/stellar/rs-soroban-env/pull/1138
