### ISSUE TITLE
Investigate Wasmi sign-extension error

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-env#968]
Users are reporting wasmi error about sign extension not being enabled. 
https://discord.com/channels/897514728459468821/1133320063995367497/1133320063995367497

**Comment by ueco-jb** [comment]
I mentioned this on a discord post, but I got this output while trying to optimize contract which fails on allocation (maybe? probably?)
```
$ soroban contract optimize --wasm pair.wasm
Reading: pair.wasm (55763 bytes)
Writing to: pair.optimized.wasm...
[wasm-validator error in function 87] unexpected false: all used features should be allowed, on
(i32.extend8_s
 (local.get $2)
)
```
but this tells me nothing, except it may be connected with this error:
```
error: transaction simulation failed: HostError: Error(WasmVm, InternalError)

Event log (newest first):
   0: [Diagnostic Event] topics:[error, Error(WasmVm, InternalError)], data:"Module(Translation(TranslationError { inner: Validate(BinaryReaderError { inner: BinaryReaderErrorInner { message: "sign extension operations support is not enabled", offset: 28307, needed_hint: None } }) }))"
   1: [Diagnostic Event] topics:[fn_call, Bytes(
...
```

**Comment by graydon** [comment]
So .. I don't _think_ the allocation failure has anything to do with sign extension. The allocator was broken! I've posted a fix to the SDK in https://github.com/stellar/rs-soroban-sdk/pull/1045 and a test that uses it (along with some budgeting fixes) to the env in https://github.com/stellar/rs-soroban-env/pull/972

But if you're seeing a sign extension error like the one reported from the CLI, I expect this is a CLI issue -- like we're prohibiting sign extension in our use of `wasm-validator` and we're not supposed to?

**Comment by heytdep** [comment]
> So .. I don't _think_ the allocation failure has anything to do with sign extension. The allocator was broken! I've posted a fix to the SDK in [stellar/rs-soroban-sdk#1045](https://github.com/stellar/rs-soroban-sdk/pull/1045) and a test that uses it (along with some budgeting fixes) to the env in #972
> 
> But if you're seeing a sign extension error like the one reported from the CLI, I expect this is a CLI issue -- like we're prohibiting sign extension in our use of `wasm-validator` and we're not supposed to?

I'm seeing the same error in a cargo test, so I don't think it's a CLI-only issue.

**Comment by heytdep** [comment]
For more context, I do think that this is directly related to the sign extension feature to not be enabled in the stellar wasmi fork. What confuses me is that I remember checking the wasmi configs for the host env a couple of months ago and the feature was also turned off. Anyways, I believe that this error is expected given that the WASM that is likely generated by https://github.com/stellar/fca00c/blob/main/soroban-asteroids/game-engine/src/map.rs#L41 contains blocks like:

```wat
block  ;; label = @3
          block  ;; label = @4
            local.get 0
            local.get 1
            i32.div_s
            local.tee 4
            local.get 0
            local.get 4
            local.get 1
            i32.mul
            i32.sub
            i32.gt_s
            br_if 0 (;@4;)
            local.get 3
            br_if 2 (;@2;)
            local.get 2
            i64.extend_i32_s
            local.get 4
            i64.extend_i32_s
            i64.mul
            local.tee 5
            i64.const 32
            i64.shr_u
            i32.wrap_i64
            local.get 5
            i32.wrap_i64
            local.tee 3
            i32.const 31
            i32.shr_s
            i32.ne
            br_if 2 (;@2;)
            local.get 1
            i32.const 2
            i32.div_s
            local.tee 4
            i32.const 0
            i32.lt_s
            local.get 3
            local.get 4
            i32.add
            local.tee 1
            local.get 3
            i32.lt_s
            i32.xor
            br_if 2 (;@2;)
            br 1 (;@3;)
          end
```

Where the sign extension feature is indeed used.

**Comment by heytdep** [comment]
It looks like signed extensions are used now also by the previous version WASM binary. I believe it might be something with the rust update that now compiles WASMs that previously weren't using sign extension features to now use it. 

In fact my WASM binary now uses `i64.extend32_s` which is what

```wat
i32.wrap/i64
i64.extend_s/i32
```

did. I believe that this optimization (one instruction instead of two) was included in the newest rust release, at least for nightly so that's why there are some WASM validation issues now.

If that is the case I believe the feature should be enabled.

**Comment by heytdep** [comment]
After taking a look at some old wasm binaries of the same contracts I'm pretty sure that this is the reason some contracts are breaking. 

This is how the WAT looked like:

```wat
i64.load offset=40
i32.wrap_i64
i64.extend_i32_s
```

and this is how it looks now using the sign extension feature:

```
i64.load offset=40
i64.extend32_s
```

**Comment by heytdep** [comment]
As a short term solution, one can compile with

```
RUSTFLAGS="-C target-cpu=mvp" cargo +nightly build --target wasm32-unknown-unknown --release -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
```

which seems to compile without sign extension opcodes. But I do not think that it should be a longer term solution. Especially because it seems that there is some sort of LLVM bug which causes `RUSTFLAGS="-C target-feature=-sign-ext"` to still compile with sign extension opcodes.

**Comment by tomerweller** [comment]
Given that rust 1.70 defaults to signed extensions and most WASM runtimes supports these it looks like we should too
