### ISSUE TITLE
Enforce max expiration ledger

### ISSUE THREAD

**Issue by dmkozh** [stellar/rs-soroban-env#973]
Currently we allow bumping entries by arbitrary amounts, but silently clamp the values at max expiration ledger. This will lead to footguns in case of temporary entries that have to live for a certain time period (such as nonces for expirable signatures). To solve this, we need to do 2 things:

- Provide max expiration ledger (or max bump amount) as a host function, so that contracts could make decisions (like we do to reject signatures/token approvals that expire too far into future)
- Return error for bumps that try bumping entry past the max expiration ledger (both for bump op and bump host fn)

**Comment by sisuresh** [comment]
Bump op doesn't need to be updated because we already return malformed if ledgersToExpires is > maxEntryExpiration - 1.
